### ISSUE TITLE
안녕하세요. 혹시 가로세로 크기 조절은 불가능한가요?

### ISSUE THREAD

**Issue by KimDwoSung0127** [nhn/gpm.unity#102]
팝업스타일로 웹뷰를 뛰우는데 웹뷰를 특정영역에만 뛰워야 하는 상황입니다.
혹시 크기 조절은 불가능한가요?

**Comment by spin-nhn** [comment]
안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

### 문의 내용
팝업 사이즈 조절 방법에 대해 문의하셨습니다.

### 답변
현재 팝업 사이즈 조절 기능은 제공하고 있지 않으며,
내부 논의 후 다시 공유드리겠습니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰 등록](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews)은 저희에게 큰 힘이 됩니다 :)

**Comment by taehyeon-nhn** [comment]
@KimDwoSung0127 안녕하세요.

GPM WebView에 크기 조정 및 위치 조정 기능이 업데이트되었습니다.
상세 내용은 [GPM WebView docs](https://github.com/nhn/gpm.unity/tree/main/docs/WebView#%EC%8A%A4%ED%8E%99)에서 확인 부탁드립니다.

이슈 클로즈 하겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
