### ISSUE TITLE
예제 씬을 만들어주실수 없나요?

### ISSUE THREAD

**Issue by JungUook** [nhn/gpm.unity#105]
유니티 2020.2.4에서 안드로이드로 빌드해봤는데 웹뷰가 안나오네요.

[api문서](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md)에 있는 showurl을 시도해봤는데
아무 반응이 없습니다.

다른 설정이 필요한가요?

**Comment by spin-nhn** [comment]
@JungUook 님 안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

## 문의 내용

Unity 2020.2.4f1에서 안드로이드 빌드 후 API 호출 시 아무런 반응이 없어, 추가 설정이 필요한지에 대해 문의하셨습니다.

## 답변

먼저 Unity 2020.2.4f1에서 테스트를 진행해 보았는데 다행히도 정상작동됨을 확인하였습니다.

아래 Flow 대로 프로젝트를 설정해 보시고, 그래도 안된다면 해당 프로젝트를 메일로 전달해 주시면 원인을 체크하여 답변드리도록 하겠습니다.

1. Unity 빈 프로젝트 생성
2. GPM Manager에서 GPM WebView 설치
3. Player Settings > Publishing Settings > Build 에서 Custom Main Gradle Template 체크 후 생성된 mainTemplate.gradle 파일에 아래 코드 추가
```gradle
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    // 이 설정을 추가합니다.
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72"
    **DEPS**
}
```
4. build

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by JungUook** [comment]
빠른 답변 감사드립니다.
해당 답변대로 진행해보니 잘 작동됩니다.

2019.3 이전 버전에서 gradle로 전환하라는 부분을 이후 버전은 안해도 된다는 것으로 이해해버렸습니다.
api문서 내용은 제대로였는데, 제가 오해를 했네요.

**Comment by spin-nhn** [comment]
@JungUook 
공유해 주셔서 감사합니다 :)
진행 중인 프로젝트 대박 나시길 기원합니다 🥇 

그리고 시간이 되시면 저희 GPM 서비스 리뷰 등록도 부탁드립니다 :)

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)
