### ISSUE TITLE
WebView에서 FullScreen모드로 띄웠는데 하단네비게이션바는 안없어 지네요. 이건 숨김 모드로 할수 없나요?

### ISSUE THREAD

**Issue by cheng80** [nhn/gpm.unity#107]
FullScreen모드로 지정 했습니다 유니티도 기본으로 몰입모드로 실행 중이고요. 
 isNavigationBarVisible = false로 했는데도 웹뷰에서만 하단바가 나타납니다.
이건 숨길수 없을까요? 현재 에셋스토에서 받은 버전은 2.0.2 입니다.

public void ShowUrl()
{
    GpmWebView.ShowUrl(
        "http://gameplatform.toast.com/",
        new GpmWebViewRequest.Configuration()
        {
            style = GpmWebViewStyle.FULLSCREEN,
            isClearCookie = false,
            isClearCache = false,
            isNavigationBarVisible = false,
            title = "The page title.",
            isBackButtonVisible = false,
            isForwardButtonVisible = false,
#if UNITY_IOS
            contentMode = GpmWebViewContentMode.MOBILE
#endif
        },
        OnOpenCallback,
        OnCloseCallback,
        new List<string>()
        {
            "USER_ CUSTOM_SCHEME"
        },
        OnSchemeEvent);
}

**Comment by spin-nhn** [comment]
@cheng80님 안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![dooray-sticker-005.png](https://nhnent.dooray.com/static_images/sticker-packs/16/pc/005.png)

### 문의 내용

FullScreen 모드 시, 하단 내비게이션 바 숨김 처리에 대한 문의를 하셨습니다.

### 답변

문의 하신 기능은 현재 GPM WebView에서 지원이 되지 않는 기능입니다.

어떤 방식으로, 어떻게 제공하면 좋을지 내부 논의 후 최대한 빠른 시일내로 적용하도록 하겠습니다.

좋은 의견 감사합니다 :)

---

GPM 서비스를 사용해 주셔서 감사합니다 :)
[AssetStore 리뷰 등록](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews)은 저희에게 큰 힘이 됩니다 :)

**Comment by spin-nhn** [comment]
@cheng80 님 안녕하세요. 김민석입니다 :)

해당 기능은 Android System 설정을 변경해야 하는 이슈가 있어서, GPM WebView에서는 추가하지 않기로 결정되었습니다.
좋은 소식 전달드리지 못해 죄송합니다.
