### ISSUE TITLE
안드로이드 웹뷰관련 질문사항

### ISSUE THREAD

**Issue by nox2454** [nhn/gpm.unity#108]
IOS에서는 오른쪽 상단에 닫기 버튼이 자동으로 생성되나
현재 저의 안드로이드빌드 에서는 뒤로가기로만 닫기 
기능이 가능합니다.

질문1 안드로이드에서도 IOS처럼 닫기버튼을 자동으로 생성하는 기능이 있나요?

질문2 안드로이드 에서 팝업웹뷰를 만들고 클로즈버튼을 따로 구현하려고하나 
          버튼이 웹뷰 에 가린듯하여 눌리지 않습니다... 웹뷰 위에 버튼을 띄우려면
          어떤 작업이 필요한지요...

미리 감사드립니다.

## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x] WebView

## Version
Write the version that you are currently using.

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by spin-nhn** [comment]
nox2454님 안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![dooray-sticker-005.png](https://nhnent.dooray.com/static_images/sticker-packs/16/pc/005.png)

### 문의 내용

Android에서 닫기 버튼이 노출되지 이슈에 대해 문의하셨습니다.

### 답변

닫기 버튼은 별다른 설정이 없어도 노출이 되어야 합니다.
iOS는 보이는데 Android가 보이지 않는 상태라면, 어떤 이유에서인지 Android 리소스가 누락되었거나 리소스 로드에 실패했을 가능성이 있습니다.

아래 정보 메일로 전달해 주시면 확인 후 답변드리도록 하겠습니다.

1. Show API 구현 코드
2. Unity 빌드 시, 오류가 발생한다면 오류 코드 
3. APK 파일

---

GPM 서비스를 사용해 주셔서 감사합니다 :)
[AssetStore 리뷰 등록](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews)은 저희에게 큰 힘이 됩니다 :)

* 문의 메일 : dl_gpm_help@nhn.com

**Comment by spin-nhn** [comment]
nox2454님 안녕하세요.

전달해 주신 UnityProject를 확인해 보니, isNavigationBarVisible이 설정되지 않아 X버튼이 노출되지 않는 것을 확인하였습니다.

WebViewManager.cs 파일의 31번째 줄에서 
Configuration 생성 코드를 아래 코드로 변경 후 다시 테스트 부탁드립니다.

```cs
new Gpm.WebView.GpmWebViewRequest.Configuration()
{
    title = "docs|GPMWebView",
    style = Gpm.WebView.GpmWebViewStyle.POPUP,
#if UNITY_IOS
    contentMode = Gpm.WebView.GpmWebViewContentMode.RECOMMENDED
#endif
}
```

그리고 Configuration의 contentMode 속성은 iOS 플랫폼에서만 적용되니 위와 같이 define으로 사용하시는 것이 좋습니다.

감사합니다 :)

**Comment by nox2454** [comment]
저걸 스크롤바라고 착각했네요,,ㅜ

신속 정확한답변 감사합니다.!!!!

**Comment by spin-nhn** [comment]
nox2454 확인 감사합니다 :)

멋진 앱 개발하시길 바랍니다.
