### ISSUE TITLE
WebView doesn't open

### ISSUE THREAD

**Issue by Jicha** [nhn/gpm.unity#111]
Hi,

I'm trying to open a webview when clicking on a cube. Using the example code provided in the class, I get this : 

```
        private void OnMouseDown()
	{
		Debug.Log("Click on cube");
		ShowUrl();
	}
	public void ShowUrl()
	{
		Debug.Log("ShowUrl");
		GpmWebView.ShowUrl(
			"http://gameplatform.toast.com/",
			new GpmWebViewRequest.Configuration()
			{
				style = GpmWebViewStyle.POPUP,
				isClearCookie = false,
				isClearCache = false,
				isNavigationBarVisible = true,
				title = "Test",
				isBackButtonVisible = true,
				isForwardButtonVisible = true,
#if UNITY_IOS
			 contentMode = GpmWebViewContentMode.MOBILE
#endif
		 },
			OnOpenCallback,
			OnCloseCallback,
			new List<string> ()
		 {
			"USER_ CUSTOM_SCHEME"
		 },
		 OnSchemeEvent);
	}

	private void OnOpenCallback(GpmWebViewError error)
	{
		Debug.Log("OnOpenCallback starting");
		if (error == null)
		{
			Debug.Log("[OnOpenCallback] succeeded.");
		}
		else
		{
			Debug.Log(string.Format("[OnOpenCallback] failed. error:{0}", error));
		}
	}

```
Unfortunately, it doesn't open anything. No error in console either. Can you help me?

Thanks

Edit : Does it work with WebGL or does it only work on the android build?

**Comment by SangYun-nhn** [comment]
Hi
Currently, WebView only supports Android and iOS platforms.
On which platform did you run the code?
And did you refer to the [guide](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.en.md) document? 
If the solution is not solved even after checking the guide document
Please give us specific information, such as the Unity version and execution environment, and we will help.

**Comment by Jicha** [comment]
Hi,

thank you for your answer. I wanted to run it in WebGL. This is probably why it won't work !

**Comment by SangYun-nhn** [comment]
@Jicha 

Hi,

I am sorry for not being able to help.
We will review if we can support the WebGL platform in the future.
Thank you for your interest in GPM.
