### ISSUE TITLE
UI InfiniteScroll Spacing 기능

### ISSUE THREAD

**Issue by jsolra** [nhn/gpm.unity#135]
Unity LayoutGroup의 Spacing과 같은 오브젝트간 간격 설정 기능은 없나요?

**Comment by SangYun-nhn** [comment]
@jsolra 
안녕하세요.
먼저 GPM을 사용해 주셔서 감사드립니다.

현재는 첫 번째 아이템 간격 설정(padding) 기능만 지원하고 있습니다.
문의하신 내용은 내부에서 검토 후 의견 드리겠습니다.

**Comment by SangYun-nhn** [comment]
@jsolra 

안녕하세요.

현재 담당자가 다른 업무와 백신 휴가로 답변이 늦어지고 있습니다.
최대한 빠르게 지원 여부를 검토해서 의견 드리도록 하겠습니다.

고맙습니다.

**Comment by smflt-nhn** [comment]
@jsolra 

안녕하세요.

담당자 장동연 입니다. 
현재는 Spacing 기능이 없으나 필요한 기능인 것으로 판단되어 빠른 시일 내 추가 할 예정입니다.
업데이트 후 전달 드리겠습니다. 

좋은 의견 감사합니다.

**Comment by smflt-nhn** [comment]
UI 2.0.7 버전에 적용되었습니다. space 인자로 조정 가능합니다.
