### ISSUE TITLE
infiniteScroll를 커스텀하려고합니다.

### ISSUE THREAD

**Issue by JungUook** [nhn/gpm.unity#136]
item에 swipe기능을 넣으려고하는데요
스크롤중에는 자꾸 x값이 고정되어버립니다.

어느항목을 수정해야 스크롤중 x값이 고정되는걸 방지할 수 있을까요?

**Comment by JungUook** [comment]
InfiniteScroll 클래스에서 SetItemSizeAndPosition함수내부에 포지션값을 유동적으로 변경하니 해결되었습니다.

**Comment by SangYun-nhn** [comment]
@JungUook 
안녕하세요.
먼저 GPM을 사용해 주셔서 감사드립니다.

현재 개발 담당자분이 백신 휴가 중이어서 아직 답을 드리지 못하고 있었습니다. ^^;
도움을 드리기 전에 해결하셨다니 다행이네요
말씀하신 swipe 기능이 어느 상황에서 필요한지, 범용적으로 니즈가 있을지 등 의견 주시면
정식 기능으로 추가할지 검토하겠습니다.

고맙습니다.

**Comment by JungUook** [comment]
swipe 기능은 우편함, 메일, 알람같은 곳에서 사용하려고 했습니다.
간단한 제스처를 통해 상태 변경 및 확인, 삭제등에 이용할 목적이었습니다.

**Comment by SangYun-nhn** [comment]
@JungUook 

넵 공유 감사합니다.
내부에서도 긍정적으로 검토하겠습니다.

다시 한번 GPM을 사용해 주셔서 감사드립니다.
