### ISSUE TITLE
웹뷰 질문드립니다.

### ISSUE THREAD

**Issue by punch5545** [nhn/gpm.unity#141]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x] WebView

## Version
최신버전

## Summary
웹뷰 사용

## Screenshots
If applicable, add screenshots to help explain your question.

## Additional context

안녕하세요.
웹뷰에서 팝업허용할 방법이 있을까요?

안드로이드 환경입니다.

**Comment by spin-nhn** [comment]
@punch5545 님 안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![image](https://user-images.githubusercontent.com/58416997/125927577-90d242b2-0544-4071-8157-58fbb9ea465a.png)

**문의 내용**
팝업 허용에 대해 문의를 하셨습니다.

**답변**
저희가 따로 막고 있진 않고요. 테스트해 보니 잘 뜨고 있는데 혹시 문제가 있으신 건가요?
좀 더 자세한 설명 부탁드립니다.

GPM 서비스를 사용해 주셔서 감사합니다 :)
AssetStore 리뷰 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by punch5545** [comment]
@spin-nhn 안녕하세요 :)

나이스평가정보의 본인인증 API를 사용하려 하는데, 웹문서의 JS에서 window.open() 함수가 실행이 안되는 듯 보입니다.

테스트해본 웹주소는 https://www.mogumogu-event.co.kr/ 입니다.

**Comment by spin-nhn** [comment]
@punch5545 님
말씀하신 부분 확인해 보니, GPM WebView에서 구현이 빠져 있는 것을 확인하였습니다.
빠른 시일 내로 다른 몇 가지 기능과 함께 배포하도록 하겠습니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by punch5545** [comment]
추가로 요청하나 드려도 괜찮을까요?
안드로이드 웹뷰 속성중에 setSupportMultipleWindows(boolean) 이라는 옵션이 있는데요,
해당 옵션을 true로 주면 팝업창이 다른 WebView 또는 OS에서 설정된 기본 브라우저에 나타나고 false로 주면 같은 창에서 나타납니다.

위에 나온 모구모구 이벤트 웹 페이지처럼 본인인증을 위해 쿠키와 세션 정보가 필요한 경우 서로 다른 웹뷰나 브라우저간 쿠키 및 세션 공유가 어렵기 때문에 해당 옵션을 ON/OFF 하는 기능이나 애초에 default를 false로 두어주셨으면 합니다.

답변주셔서 정말 감사합니다 😊

**Comment by spin-nhn** [comment]
@punch5545 님
setSupportMultipleWindows(boolean) 옵션을 false로 설정하면,
팝업 느낌의 전환이 아닌, 현재 페이지 전환 느낌으로 표현이 될듯한데. 괜찮으실까요?
해당 페이지에서 테스트를 해 봤는데 인증까지 다 되긴 합니다 :)

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by punch5545** [comment]
네 괜찮습니다 :) 릴리즈는 언제쯤 진행될까요?

**Comment by spin-nhn** [comment]
@punch5545 님
issue #142 이슈 처리와 함께 금주 또는 차주 중으로 배포 진행하도록 할 예정입니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by punch5545** [comment]
정말감사합니다 :)

**Comment by punch5545** [comment]
선생님! MEMU 앱플레이어에서는 팝업이 뜨는데 모바일에서는 안뜨네요.....?

ttauth.cafe24.com 여기서 휴대폰 인증창입니다.

**Comment by spin-nhn** [comment]
@punch5545 님 안녕하세요 :)

ttauth.cafe24.com 휴대폰 인증 창이 안 뜨는 것도 동일한 이슈이고요 ^^
테스트해 보니 잘됩니다.

배포까지 조금만 기다려 주시면 감사하겠습니다 :)

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by punch5545** [comment]
넵 답변 감사합니다.

클라이언트가 자꾸 재촉해서요 ....ㅠㅠ

**Comment by spin-nhn** [comment]
@punch5545 님 안녕하세요 :)
금일 GPM WebView v1.3.0이 배포되었습니다.

configuration에 supportMultipleWindows 속성이 추가되었구요.
사용법은 아래 가이드 참고 부탁드립니다.

[GPM WebView Guide](https://github.com/nhn/gpm.unity/tree/main/docs/WebView)

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by punch5545** [comment]
정말 감사합니다 nhn 선생님들 ㅠㅠㅠㅠ
