### ISSUE TITLE
Webview위에 Unity UI 랜더링 방법 문의

### ISSUE THREAD

**Issue by stopfire00** [nhn/gpm.unity#144]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x] WebView

## Version
GPM Webview 1.2.0

## Summary
UICanvas -> Webview -> UICanvas등의 순서로 Webview위에 Unity UI를 띄우고 싶은데 가능한 방법이 있나요?

**Comment by spin-nhn** [comment]
@stopfire00 님 안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![image](https://user-images.githubusercontent.com/58416997/127421364-d605d26d-87e9-4e21-9362-6064ac33920d.png)

**문의 내용**

GPM WebView 위에 Unity UI를 렌더링하는 방법에 대해 문의하셨습니다.

**답변**

현재 GPM WebView는 해당 기능을 지원하지 않습니다.
내부 논의는 되고 있으나, 지금 당장은 지원이 어려운 상황입니다.
좋은 소식을 전해드리지 못해 죄송합니다.

@stopfire00 님의 멋진 프로젝트를 항상 응원하겠습니다.

감사합니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by stopfire00** [comment]
바쁘신 와중에 답변 감사드리며,
더 나은 발전을 위해 힘써주셔서 감사 합니다.

오늘도 즐거운 하루 되세요~
감사합니다.
