### ISSUE TITLE
WebView를 3D로 월드에 생성가능한가요? VR모드로요

### ISSUE THREAD

**Issue by LeeDongYoun** [nhn/gpm.unity#149]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x] WebView

## Version
Write the version that you are currently using.

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by spin-nhn** [comment]
@LeeDongYoun 님 안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![image](https://user-images.githubusercontent.com/58416997/127421364-d605d26d-87e9-4e21-9362-6064ac33920d.png)

**문의 내용**

[VR] 3D 월드에 GPM WebView를 생성할 수 있는지 대해 문의하셨습니다. 

**답변**

현재 GPM WebView는 해당 기능을 지원하지 않습니다.
내부 논의는 되고 있으나, 지금 당장은 지원이 어려운 상황입니다.
좋은 소식을 전해드리지 못해 죄송합니다.

@LeeDongYoun 님의 멋진 프로젝트를 항상 응원하겠습니다.

감사합니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)
