### ISSUE TITLE
[질문] 웹뷰 설치를 시도하면 "서비스를 설치하지 못했습니다."라는 에러가 발생합니다.

### ISSUE THREAD

**Issue by blackwitch** [nhn/gpm.unity#150]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [x] Manager
* [ ] UI
* [ ] WebView

## Version
WebView 1.3.0 / Unity 2020.03.12f1 / Windows

## Summary
  GPM 설치 후 WebView 인스톨을 시도하면 "서비스를 설치하지 못했습니다."라는 메세지가 뜹니다.

## Screenshots
![image](https://user-images.githubusercontent.com/6980454/128669589-0fcfbdbb-490a-4630-aa8d-eafe0edd534e.png)

## Additional context
-

**Comment by smflt-nhn** [comment]
안녕하세요. 장동연입니다.
우선 GPM을 사용해주셔서 감사합니다.

해당 내용은 프로젝트의 currentDirectory설정이 "/Asset/.."가 붙어서 경로를 찾지 못하는 것으로 예상됩니다.
첨부 드린 압축 파일에서 CompressImplementation.cs를 교체 후 테스트 정상 작동하는지 확인 부탁 드립니다.
[CompressImplementation.zip](https://github.com/nhn/gpm.unity/files/6960356/CompressImplementation.zip)

정상 작동이 확인된다면 다음 버전에 포함 시켜 배포할 예정입니다.

감사합니다.

**Comment by blackwitch** [comment]
알려주신 내용으로 재시도 해보았으니 같은 문제가 발생합니다.

![image](https://user-images.githubusercontent.com/6980454/129289081-d9d4bffc-e2d7-4c09-87b0-f8377dcd7f58.png)

**Comment by smflt-nhn** [comment]
피드백 주셔서 감사합니다.
파일이 없거나 찾을 수 없어 발생하는 에러라 추정되는데우선 발생 원인이 cmd때문인지 확인하길 희망합니다.
저 링크와 같이 cmd들어가서 ipconfig와 같은 명령어를 쳤을 때 동작 하나요?
또는 "메시지:  오른쪽에 있는 경로의 7z.exe파일이 있는지도 확인 부탁 드립니다.

**Comment by blackwitch** [comment]
![image](https://user-images.githubusercontent.com/6980454/129652835-34cc9426-4845-422e-91e5-b07a635c9652.png)
해당 파일은 존재하는 것으로 확인했습니다.

**Comment by smflt-nhn** [comment]
안녕하세요. 다음 업데이트부터는 시스템 환경과 상관없이 동작하도록 개선하고자 합니다.
수정된 패키지 전달 드립니다. 해당 패키지로 잘 되는지 확인 부탁 드립니다.
[gpm_manager_v2.0.4_fixed.zip](https://github.com/nhn/gpm.unity/files/7004481/gpm_manager_v2.0.4_fixed.zip)

**Comment by blackwitch** [comment]
금일 GPM을 다시 설치해 WebView를 재설치하니 정상적으로 설치되는 것을 확인 했습니다. 

감사합니다. :)
