### ISSUE TITLE
안녕하세요 웹뷰 사용시 AndroidJavaException: java.lang.NullPointerException 에러 발생 문제입니다ㅠ

### ISSUE THREAD

**Issue by devkimluxxNewto** [nhn/gpm.unity#151]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ v ] WebView

## Version
Common 2.0.4
Communicator 1.0.2
WebView 1.3.0

## Describe the bug
ShowHtmlString()함수 실행할 때 오류가 떠서, 단순 URL 열기 구현으로 테스트했는데,  ShowUrl 함수 호출로도 에러가 발생합니다..ㅠ

아래는 구현 예제입니다. (콜백에 null 말고 예제에 나온 함수로 넣어도 같은 증상입니다)
Gpm.WebView.GpmWebView.ShowUrl("http://www.naver.com", new Gpm.WebView.GpmWebViewRequest.Configuration()
            {
                style = Gpm.WebView.GpmWebViewStyle.FULLSCREEN,
                isClearCookie = false,
                isClearCache = false,
                isNavigationBarVisible = true,
                title = "네이버",
                isBackButtonVisible = true,
                isForwardButtonVisible = true,
#if UNITY_IOS
            contentMode = GpmWebViewContentMode.MOBILE
#endif
            }, null, null, null, null);

## Screenshots
![image](https://user-images.githubusercontent.com/67044408/128683557-aa75a965-b799-40aa-9016-b3e505ba0c09.png)
관계가 있을지는 모르겠지만, 스크린샷에 나온 에러 발생보다 위쪽에 Error libprocessgroup set_timerslack_ns write failed: Operation not permitted 에러도 발생하였습니다.

### Unity
- 2020.3.12f1

### Desktop (please complete the following information):
 - OS: Windows 10

### Smartphone (please complete the following information):
 - Device: Galaxy S21 Ultra
 - OS: Android 10

**Comment by spin-nhn** [comment]
@devkimluxxNewto 님 안녕하세요. GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![image](https://user-images.githubusercontent.com/58416997/128956037-b25a65e4-2aab-4310-abed-603c55b90839.png)

**문의 내용**

ShowHtmlString API 호출 시, NullPointerException이 발생하는 이슈에 대해 문의하셨습니다.

**답변**

GPM WebView v1.3.0에서 NavigationBar 색상 변경 기능이 추가되었는데, 설정이 빠져서 발생한 오류입니다.
개발 시, 색상이 비어 있을 경우 기본 값을 설정했어야 하는데 놓친 것 같습니다 T^T

일단 아래와 같이 configuration 설정 시 색상 값을 추가해 주시면 해당 이슈는 해결되며,
다음 업데이트 시 색상에 기본 값을 추가해 놓도록 하겠습니다.

**Code**

```cs
new GpmWebViewRequest.Configuration()
{
    // ...
    navigationBarColor = "#4B96E6",
    // ...
}
```

**Guide**

* [GPM WebView ShowHtmlString](https://github.com/nhn/gpm.unity/tree/main/docs/WebView#showhtmlstring)

불편을 드려 죄송합니다. 

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by spin-nhn** [comment]
@devkimluxxNewto 님 안녕하세요. 김민석입니다.
금일 해당 이슈 수정하여 GPM WebView v1.3.1 으로 배포 완료되었습니다 :)

![image](https://user-images.githubusercontent.com/58416997/129127894-93ddf599-a2a8-4b90-837a-89c817b8d102.png)

@devkimluxxNewto 님의 개발력 향상을 항상 응원하겠습니다 :)

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)
