### ISSUE TITLE
WebView의 위치/사이즈 설정에 관하여.

### ISSUE THREAD

**Issue by elecgon72** [nhn/gpm.unity#152]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x ] WebView

## Version
1.3.0

## Summary
안녕하세요.
WebView관련해서 문의를 드리고 싶습니다.
현재 팝업모드로 WebView를 표시할 때 표시 시작위치와 사이즈 (Rect)를 지원하고 있는지 알고 싶습니다.
파라메터에는 이런 정보가 없는 것 같아서 확인차 문의 드립니다.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by spin-nhn** [comment]
@elecgon72 님 안녕하세요 GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![image](https://user-images.githubusercontent.com/58416997/127421364-d605d26d-87e9-4e21-9362-6064ac33920d.png)

**문의 내용**

팝업 오픈 시, 사이즈 및 위치 변경 기능에 대해 문의하셨습니다.

**답변**

현재 GPM WebView는 해당 기능을 지원하지 않습니다.
내부 논의는 되고 있으나, 지금 당장은 지원이 어려운 상황입니다.
좋은 소식을 전해드리지 못해 죄송합니다.

@elecgon72 님의 멋진 프로젝트를 항상 응원하겠습니다.

감사합니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by taehyeon-nhn** [comment]
@elecgon72 안녕하세요.

GPM WebView에 크기 조정 및 위치 조정 기능이 업데이트되었습니다.
상세 내용은 [GPM WebView docs](https://github.com/nhn/gpm.unity/tree/main/docs/WebView#%EC%8A%A4%ED%8E%99)에서 확인 부탁드립니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
