### ISSUE TITLE
WebView 사이즈 조절 및 위치이동 

### ISSUE THREAD

**Issue by stevejobsElon** [nhn/gpm.unity#156]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [✓] WebView

## Version
1.3.0
## Development 

 Unity, IOS ,Android

## Current Behavior

사이즈 조절 및 위치 조정 가능 하게 됐음 좋겠어요  
그럼 원하는 위치에 넣어서 보여주기가 좋을거 같습니다.
수고하세요~  화이팅!

## Expected Behavior
Write a description of the future action.

**Comment by spin-nhn** [comment]
@stevejobsElon 님 안녕하세요. GPM WebView를 담당하고 있는 김민석이라고 합니다.
먼저 GPM 서비스를 사용해 주셔서 감사의 인사를 드립니다.

![image](https://user-images.githubusercontent.com/58416997/127421364-d605d26d-87e9-4e21-9362-6064ac33920d.png)

**문의 내용**

WebView 팝업 모드 시, 사이즈 조절 및 위치 조정에 대해 문의하셨습니다.

**답변**

해당 기능은 현재 추가 예정 중입니다.
다만 현재 개발 리소스가 부족하여 딜레이가 되고 있습니다 T^T
예정되어 있는 업무를 최대한 빨리 처리하고, 기능을 추가할 수 있도록 열심히 달리겠습니다 :)

![image](https://user-images.githubusercontent.com/58416997/130586411-c2d15b26-4c51-4103-afc6-42839996a177.png)

감사합니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
[AssetStore 리뷰](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#reviews) 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by taehyeon-nhn** [comment]
@stevejobsElon 안녕하세요.

GPM WebView에 크기 조정 및 위치 조정 기능이 업데이트되었습니다.
상세 내용은 [GPM WebView docs](https://github.com/nhn/gpm.unity/tree/main/docs/WebView#%EC%8A%A4%ED%8E%99)에서 확인 부탁드립니다.

이슈 클로즈 하겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
