### ISSUE TITLE
GpmWebView.ShowUrl 반응이 없습니다.

### ISSUE THREAD

**Issue by blackwitch** [nhn/gpm.unity#157]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x] WebView

## Version
Windows / Unity 2020.3.12f1 / WebView 1.3.1 / Android 빌드

## Summary
공식 문서의 grandle 설정은 처리했습니다.

GpmWebView.ShowUrl("https://naver.com", ... 로 코드를 추가해 두었으나 아무런 에러도 없고, 창도 뜨지 않습니다.

혹시 Unity 툴에서 실행할 때는 아무것도 안뜨나요? 실기에서만 작동되나요?

## Screenshots
아무 반응이 없어 스샷을 넣을 수 없습니다. ^^a

## Additional context
웹뷰가 작동하는 풀 샘플 코드가 있는 아티클이 있다면 링크 부탁드립니다.

**Comment by SangYun-nhn** [comment]
@blackwitch 

안녕하세요.
GPM을 사용해 주셔서 감사드립니다.

1. Unity 툴 실행
말씀하신 Unity 툴이 Unity Editor라고 생각하고 답변 드리겠습니다 :)

WebView는 Andoid, iOS 플랫폼만을 지원하고 있으며, Unity Editor에서는 실행을 확인하실 수 없습니다.
현재로서는 Android, iOS 플랫폼 빌드를 통해서 확인이 가능하십니다.

2. 샘플 코드
공식 샘플은 아직 없지만, 도움이 드릴 수 있는 코드나 방법이 있을지 담당자를 통해 확인 드리도록 하겠습니다.

고맙습니다.

**Comment by blackwitch** [comment]
Unity Editor에서는 확인이 불가능하군요. 가능하면 추가해 주시면 좋겠습니다. 

답변 감사합니다. :)
