### ISSUE TITLE
InfiniteScroll의 오브젝트 배치 확장 기능에 대한 문의

### ISSUE THREAD

**Issue by lumiereent** [nhn/gpm.unity#161]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [x] UI
* [ ] WebView

## Version
Write the version that you are currently using.

## Development Environment
Write the version of Unity, OS and so on.

## Current Behavior
InfiniteScroll의 오브젝트 배치 확장 기능에 대한 문의

## Expected Behavior
저희가 사용하는 게임은 InfiniteScrollItem이 세로로 무한 스크롤이 되더라도
오브젝트가 가로로 2,3개씩 배치된 이후 세로열로 넘어가는 경우가 많은데 
이럴때 구현하기가 참 번거로워서 기능문의 드려요 
item Prefab의 RowCount를 지정할 수 있으면 너무 좋겠어요

**Comment by smflt-nhn** [comment]
@lumiereent
2.3.0에 해당기능 적용되어 배포되었습니다.
사용 방법은 가이드 참고 바랍니다.
감사합니다.

**Comment by lumiereent** [comment]
정말 감사합니다.

2022년 3월 23일 (수) 오전 10:33, 장동연 ***@***.***>님이 작성:
