### ISSUE TITLE
안녕하세요 gpm 너무 잘 쓰고 있습니다. 아이핀인증 관련해서 질문드려요

### ISSUE THREAD

**Issue by Roksan4614** [nhn/gpm.unity#163]
웹뷰 사용중입니다. 
아이핀 인증 중에 진행이 안되어서요.
아이디 비번 이후 2차 비밀번호 입력창이 떠야 하는데, 다시 아이디 비번 입력하게 됩니다.
어떻게 해야 할지 조언 부탁드릴게요.

**Comment by SangYun-nhn** [comment]
@Roksan4614 

안녕하세요.
GPM을 사용해 주셔서 감사드립니다 :)

WebView를 사용하시는거죠?
올려주신 내용으로는 저희가 도와드리고 싶어도 어떤 상황인지, 구체적으로 알기가 어려워서 쉽지 않을 것 같습니다.

사용하시는 서비스명과 버전과
구체적으로 어떤 상황인지를 설명 부탁드리며, 저희가 재현 가능한 부분이 있는지,
확인할 수 있는 로그 등이 있는지도 같이 알려주시면
도움을 드릴 수 있을 것 같습니다.

고맙습니다.

**Comment by Roksan4614** [comment]
유니티로 작업했고요 gpmwebview 1.3.1 사용중입니다.
웹뷰로 아이핀 인증 작업중이었는데요.
아이핀 인증을 하려면 아이디 비번 확인 후에 2차 인증을 해야 하는데요.
안드로이드는 잘 됩니다. 그런데 아이폰에서는 아이디 비번 문자입력 후 확인을 누르면
2차 인증으로 넘어가지 않고, 아이디 비번 입력창이 비어지면서 다시 입력하게 됩니다.

예전에 uiwebview 썼을 때 multiplewindow 설정을 해서 해결했던 것 같기도 한데
이 옵션은 안드로이드에서만 쓰인다고 하더라고요.

제 설명이 많이 미흡하네요 죄송합니다. 또 필요하신 정보가 있으실까요?

**Comment by SangYun-nhn** [comment]
@Roksan4614 

Android에서는 정상 동작을 하는데 iOS에서만 2차 인증으로 넘어가지 않는거군요
Android, iOS에서의 로그 비교 등을 통해서 차이점을 확인하시는 것도 방법일 것 같고요
아니면 제작하신 앱내 웹뷰가 아닌 브라우저를 통해서 해당 페이지가 정상 동작하는지도 확인을 하시면 문제 파악하는데 도움이 될 것 같습니다.

그리고 저희가 직접 확인 할 수 있는 방법을 알려주시면 테스트 해보겠습니다.

**Comment by Roksan4614** [comment]
일반 브라우저에서는 잘 됩니다.
아직 테스트 버전중이라 직접 확인하실 수는 없을것 같네요 ㅜ

예전에 uiwebview 썼을 땐 supportmultiplewindow 를 true 주는 것으로 해결했었거든요
아이폰에서도 이 부분 적용되게 할 수 잇는 방법이 없을까요?

**Comment by SangYun-nhn** [comment]
@Roksan4614 

#141 이슈에서 Android에 대한 대응만 한 상태네요
iOS 환경에서 해당 기능에 대해 담당자 확인이 필요할 것 같습니다.

확인 후 댓글 드리도록 하겠습니다.

**Comment by Roksan4614** [comment]
@SangYun-nhn 
안녕하세요 수고하십니다.
혹시 어떻게 되고 있을까요??
바쁘실텐데 죄송합니다

**Comment by SangYun-nhn** [comment]
@Roksan4614 
안녕하세요.
담당자가 다른 일정으로 바쁜 상황이어서 수일 내로 답을 드릴 수 있는 상황이 아닌 것 같습니다.
빠르게 도움을 드리고 싶은데 여의치 않아서 죄송합니다.

담당자가 가능한 일정에 최대한 빠르게 확인하여 답을 드릴 수 있도록 노력하겠습니다.
감사합니다.

**Comment by sanghyun-nhn** [comment]
@Roksan4614 
안녕하세요.

이슈를 확인해본 결과, iOS에서 2차 본인인증 화면으로 이동하자마자 이전 페이지를 다시 로드되면서 말씀하신 현상이 발생하고 있었습니다.
이슈 해결을 위해 iOS SDK의 수정이 필요하며 수정된 내용은 다음 릴리즈에 반영될 예정입니다.
다음 버전이 릴리즈된 후에 업데이트를 부탁드리겠습니다.

이슈를 제보해주셔서 감사합니다.

**Comment by Roksan4614** [comment]
@sanghyun-nhn 
네 답변 감사합니다.

혹시 업데이트가 되면 유니티 내
Game Package Manager / WebView 에 업데이트가 뜨게 될까요??

**Comment by SangYun-nhn** [comment]
@Roksan4614 
안녕하세요

넵 Game Package Manager에서 업데이트 가능한 서비스의 경우는 
그림과 같이 서비스명 앞에 아이콘이 다르게 표시되며, Update 버튼이 활성화됩니다 :)

![스크린샷 2021-11-19 오후 3 43 12](https://user-images.githubusercontent.com/26250555/142577514-f70cc16b-ae96-44cb-866a-cff2d226552e.png)

**Comment by sanghyun-nhn** [comment]
@Roksan4614 
상기 이슈가 수정된 GPM WebView v1.3.2가 배포되었습니다.
v1.3.2버전으로 업데이트한 후에 다시 확인을 부탁드립니다.
