### ISSUE TITLE
WebView 아이폰 빌드 후 동작시 튕김현상

### ISSUE THREAD

**Issue by iespero** [nhn/gpm.unity#164]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [v] WebView

## Version
gpm(최신) // 21.11.20기준

## Describe the bug
아이폰 빌드 후 -> 아이폰에서 웹뷰실행시 죽는현상

## To Reproduce

안녕하세요. Webview기능을 사용 하고있습니다.
Iphone 빌드시 필요한 작업들은 다 했고, 첫 빌드는 성공적이였습니다.
Webview가 너무 깔끔하고 좋더라구요!!
그런데 UI 수정을 간단한게 하고 , 다시 빌드시 Webview동작을 누르면 앱 자체가 죽더라구요 ㅠㅠ
그래서 다양하게 시도를 해보았습니다. 처음 한번은 GPM 플러그인을 지웠다 새로 설치후 빌드를 했는데, 웹뷰 동작이 잘 되었지만 그 이후로 다시 빌드하면 안되더라구요 ㅠㅠ
그리고 또 한번은 수십번 반복 하다보니 한번 성공을 하게 되었는데, 또 다시 빌드를 하게되면 안되더라구요 ㅜㅜ
아이폰 빌드시 유의점은 잘 적용된 상태이고, 빌드가 성공하고 Webview쪽 수정이 아닌 다른 쪽 UI수정만 있었던거라 영향이있는것도 아닙니다.
도와주세요 ㅜㅜ

## Environment
- xcode 12 사용했습니다.
### Unity
- Unity3d(20.3.14)

### Desktop (please complete the following information):
 - MAC 21.11.20 최신버전입니다.

### Smartphone (please complete the following information):
 - Iphone11pro, iphone6, ipad 등 모든 ios에서 그렇습니다. (한번 빌드 잘 될때는 잘됩니다.)

**Comment by sanghyun-nhn** [comment]
@iespero 
안녕하세요 :)

GPM을 이용해주셔서 감사합니다.

문의 내용만으로는 정보가 부족하여 원인을 파악하기가 어려운데요. Crash가 발생할 때 Crash Log나 관련된 Error Log가 있다면 공유해주실 수 있을까요?

그리고 혹시 Xcode 프로젝트 설정이 처음 GPM을 설치한 시점과 이 후 재빌드 시점이 서로 다른 점이 없는지도 확인을 부탁드립니다.

**Comment by SangYun-nhn** [comment]
@iespero 

안녕하세요.
추가 답변이 없으셔서 이슈는 클로즈 하겠습니다.

추가 요청 사항이 있으실 경우 언제든지 편하게 이슈 등록 부탁드립니다.

고맙습니다.
