### ISSUE TITLE
(WebView) 커스텀스키마 콜 시 ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by doo82112** [nhn/gpm.unity#168]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x] WebView

## Version
gpm 2.05
unity 2021.1.6f1

가이드 문서대로 따라 테스트 하고 있습니다.

스키마 콜은 단순 <a hreaf="customs://mylink"> 식으로 html 만들어서 넣었고

페이지를 showurl api사용하여 스키마 등록하여 오픈하여 해당 링크를 클릭하였습니다.

페이지는 정상 오픈되었고 해당 링크를 클릭하였을때 

ERR_UNKNOWN_URL_SCHEME 페이지만 나오고 있습니다.

가이드문서에는 언급이 없는 수정사항은
 AndroidManifest.xml에 usesCleartextTraffic="true" 를 추가하였고
스키마 오류가 나오는 바 intent-filterdp data android:scheme 등을 이것저것 검색하여 수정도 해보았습니다.
AndroidManifest 수정이 필요하다면 관련된 언급이나 문서가 있을까요?

**Comment by doo82112** [comment]
html파일에는 a hreaf="cusscheme://action">링크</a>

**Comment by sanghyun-nhn** [comment]
@doo82112 
안녕하세요 :)
GPM WebView를 이용해주셔서 감사합니다.

HTML 파일에 링크된 scheme과 ShowUrl API 호출 시 등록한 scheme이 `cusscheme://`와 동일한지 우선 확인을 부탁드립니다.
scheme이 일치하지 않을 경우, 등록되지 않은 scheme으로 판단되어 문의주신 현상과 같이 에러가 발생할 수 있습니다.

**Comment by doo82112** [comment]
와... 말씀 감사합니다.
여태 동일한 스키마를 등록했다고 생각했는데
스키마 구분자(://) 를 안쓰고 있었네요
당연하다고 생각했던 부분을 잊고 있었습니다.
암튼 감사히 잘쓰겠습니다.
