### ISSUE TITLE
웹뷰 fullscreen 으로 설정했는데, 왼쪽 영역에 빈공간이 있습니다.

### ISSUE THREAD

**Issue by Roksan4614** [nhn/gpm.unity#169]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ v] WebView

## Version
1.3.2

## Development Environment
유니티로 개발, 안드로이드 환경

## Current Behavior
Write a description of the current operation.

## Expected Behavior
Write a description of the future action.

풀스크린으로 화면을 띄웠는데 왼쪽에 공간이 생기더라고요.
빈공간 없이 가능할까요??

![image](https://user-images.githubusercontent.com/93106251/145326286-2eb4c3eb-e07d-4569-9508-6a7f5d8f172a.png)

**Comment by sanghyun-nhn** [comment]
@Roksan4614 
안녕하세요 :)

GPM을 이용해주셔서 감사합니다.

이슈 확인을 위해 좀 더 자세한 정보가 필요하여 아래 내용에 대해 확인을 부탁드립니다.

1. ShowUrl 호출 시 전달한 파라미터 정보
2. 유니티 버전
3. 상기 이슈가 발생한 디바이스 모델명
4. 특정 디바이스에서만 발생하는 것인지 아니면 모든 디바이스에서 동일한 현상이 발생하는지

**Comment by Roksan4614** [comment]
safearea 이슈같긴 한데, 뒤에 내용 안나오게 하는 것으로 처리하겠습니다. 죄송합니다.

**Comment by SangYun-nhn** [comment]
@Roksan4614 

안녕하세요

좋은 서비스를 제공하기 위해서는 피드백이 중요합니다.
그러니 죄송해 하실 필요 없습니다 :)
편하게 사용하시고 편하게 문의주세요.

고맙습니다.
