### ISSUE TITLE
본인인증 도중 Pass 로 인증하려고 하는데 계속 설치쪽으로 넘어가는데, 조언 좀 부탁드립니다.

### ISSUE THREAD

**Issue by Roksan4614** [nhn/gpm.unity#174]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.
common 2.0.8
webview 1.3.2

## Development Environment
Write the version of Unity, OS and so on.

unity 4.16f1
안드로이드 모든 기종

## Current Behavior
Write a description of the current operation.

## Expected Behavior
Write a description of the future action.

우선 너무 자주 글을 남기는 것 같아서 죄송합니다.ㅜㅜ

나이스아이디에서 제공하는 본인인증을 이용중입니다.
통신사 선택하고 pass 로 인증하기를 누르면
pass 앱이 실행되어야 하는데 설치페이지로 넘어갑니다.
pass 는 이미 설치가 되어 있고 다른 앱에서는 잘 사용하고 있습니다.
그리고 IOS 는 잘 된다고 합니다. 제가 직접보진 못하고 qa 분에게 전달받았습니다.

나이스아이디 측에 문의해 보니 웹뷰 설정을 해줘야 한다고하는데요.

viewport가 혀용되어야 한다는것과

webView.getSettings().setUseWideViewPort(true); 
webView.getSettings().setLoadWithOverviewMode(true); 

<필수설정> 
setJavaScriptEnabled(true); // 웹뷰 내 javascript 이용 여부 
setDomStorageEnabled(true); // 웹뷰 내 로컬스토리지 이용 여부 
setJavaScriptCanOpenWindowsAutomatically(true); // 웹뷰 내 window.open() 허용 여부 
setWebViewClient(new DemoWebViewClient()); // 웹뷰 내 URL별 분기 처리 
// (DemoWebViewClient 클래스 참고) 

이렇게 가이드 문서에 적시하고 있습니다.
하지만 gpm 관련해서 어디서 어떻게 설정해야 할지 모르겠더라구요.

조언부탁드릴게요ㅜㅜ

**Comment by sanghyun-nhn** [comment]
@Roksan4614 
안녕하세요 :)

문의에 언급하신 설정은 GPM WebView 내부에서 모두 알맞게 설정을 하고 있습니다. 설정의 문제는 아닌 것으로 보이네요.

- setUseWideViewPort(true);
- setLoadWithOverviewMode(true);
- setJavaScriptEnabled(true);
- setDomStorageEnabled(true);
- setJavaScriptCanOpenWindowsAutomatically(true);

Pass 앱이 실행되지는 않지만 구글 스토어 내 설치 페이지로 이동했다는 것일까요? 
설치 페이지로 이동했다는 것은 URL scheme이 정상적으로 전달은 된 것으로 보입니다만 OS 내에서 앱 설치 여부를 판단하여 자동으로 처리해주기 때문에 다른 문제일 가능성도 있을 것 같습니다.

Pass 인증하기 버튼 클릭 시 호출되는 URL을 알려주시면 확인해보도록 하겠습니다.

**Comment by Roksan4614** [comment]
웹뷰 내에서 이동하는거라 제가 url 을 알아낼 수는 없지 않나요? 유니티로 개발중인데 혹시 androidmanifest 쪽 설정 문제이려나.. 으으 url 은 어떻게 하는 방법이 있나요?

**Comment by Roksan4614** [comment]
2022-01-03 15:40:12.694 27679-27679/? D/WebViewManager: [GPM][WebView][Android][WebViewManager] shouldHandleCustomScheme : intent://requestktauth?appToken=521110D299C61BD1C036#Intent;scheme=ktauthexternalcall;action=android.intent.action.VIEW;category=android.intent.category.BROWSABLE;package=com.kt.ktauth;end

2022-01-03 15:40:12.696 1275-3912/? I/ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=market://details?id=com.kt.ktauth cmp=com.android.vending/com.google.android.finsky.activities.MarketDeepLinkHandlerActivity} from uid 10433

연결해서 확인해보니 이렇게 왔습니다.
디바이스에 pass 앱 재설치도 해보고 했습니다만, 여전히 설치 페이지로 넘어가네요

**Comment by sanghyun-nhn** [comment]
@Roksan4614 
알려주신 URL이 호출될 경우, 내부에서 패키지명이 com.kt.ktauth인 앱이 설치되어 있는지를 우선 확인하고 앱이 설치되어 있지 않은 경우 앱 설치를 위해 market scheme으로 호출해주고 있습니다. 
말씀하신 현상은 Pass by KT 앱이 설치되지 않은 상태로 인식하는 것으로 보이며 GPM WebView 내부 로직에서는 문제가 없어보입니다.

Pass by KT 앱의 패키지명이 com.kt.ktauth 인것으로 보입니다만 디바이스에 설치한 앱은 Pass by KT 앱일까요?

통신사별로 Pass 앱이 각각 제공되는데 디바이스의 USIM에 해당하는 앱만 설치가 가능하게 되어있으므로 이에 맞게 세팅이 된 것인지 다시 확인을 부탁드립니다.

**Comment by Roksan4614** [comment]
설치된 앱은 Pass by KT 앱입니다. 참고로 다른 앱에서는 모두 pass 앱이 잘 실행이 되기 때문에 디바이스 세팅문제는 아닌듯 합니다.

**Comment by sanghyun-nhn** [comment]
@Roksan4614 님이 테스트한 것처럼 동일하게 제가 보유한 디바이스에서 Pass by KT 앱을 설치하고 알려주신 URL로 테스트해봤을 때 정상적으로 Pass 앱이 설치된 것으로 인식하고 실행되네요. (Galaxy S9, Android 10)

문제가 되는 기기에서 아래의 android native 코드를 호출했을 때 반환되는 값이 null인지 확인을 한번 부탁드립니다.
만약 null이라면 설치된 앱을 인식을 못하는 상태이기 때문에 이 부분은 다른 쪽의 문제라고 생각되네요.

context.packageManager.getLaunchIntentForPackage("com.kt.ktauth")

그리고 다른 KT 기기에서도 동일한 현상이 발생하는지 확인이 가능하다면 확인을 부탁드립니다.

**Comment by Roksan4614** [comment]
저희 회사 안드로이드 테스트 기기에서 모두 설치페이지로 넘어가고 있습니다. 알아보니 android 11 에서 변경점이 있다고 합니다. manifest 쪽에서 queries 부분을 추가해 주라고 하는데.. 계속 알아보고 있습니다. 담당자분께서 확인해보셧다고 하셧는데, 혹시 android 11이 맞는지, manifest 쪽에 com.kt.ktauth 관련된 추가 내용이 있는지 확인해 주실 수 있을까요?? 번거럽고 해드려서 죄송합니다.

**Comment by sanghyun-nhn** [comment]
@Roksan4614 
Android 10 버전에서 확인했고 manifest에 추가된 queries 부분은 없습니다.

관련해서 내용을 찾아보니 해결방법은 아래 방법 중 하나로 하면 될 것 같습니다. 링크된 가이드 문서를 참고하세요.
(https://developer.android.com/training/package-visibility/declaring?hl=ko)
- targetSdkVersion을 29로 지정
- 설치 확인 & 실행이 필요한 앱의 패키지명을 manifest 파일에 queries에 추가
- manifest 파일에 QUERY_ALL_PACKAGES 권한 추가(추천하지 않음)

**Comment by Roksan4614** [comment]
감사합니다. 처리 되었습니다. 유니티나 안드로이드 버전업이 될때마다 설정관련 쪽도 계속 신경을 써야 하네요. 감사합니다.
