### ISSUE TITLE
안드로이드에서 스킴이벤트가 웹뷰를 꺼줘야 실행이 됩니다.

### ISSUE THREAD

**Issue by Roksan4614** [nhn/gpm.unity#176]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

common 2.0.8
webview 1.3.2

## Development Environment
Write the version of Unity, OS and so on.

unity 4.19f1

## Current Behavior
Write a description of the current operation.

Pass 앱 인증을 완료하면 스킴이벤트가 동작하면서 앱이 꺼지게 해놨는데
웹뷰가 하얀상태에서 멈춰있습니다.
그러다가 x를 눌러서 웹뷰를 직접 꺼주면 그제서야 스킴이벤트가 돌아갑니다.

ios는 정상인것을 보면 androidmanifest 쪽 이슈같은데 ㅜㅜ

혹시 조언을 얻을 수 있을까 해서 글 남깁니다 ㅜㅜ

네이버와 카카오같은 경우 웹뷰를 띄우고 로그인을 하고 있는데, 이 두가지는 아주 잘됩니다.
로그인이 완료가 되면 정상적으로 스킴이벤트를 받아 웹류를 꺼주고 있습니다.

그런데 이 pass 인증만 완료를 해도 하얗게만 보이고 스킴이벤트가 동작 안하다가
앱을 꺼줘야만 동작하는것이 이상합니다ㅜㅜ

## Expected Behavior
Write a description of the future action.
웹뷰에서 pass 인증 하면 스킴이벤트가 동작했으면 좋겠습니다.

**Comment by taehyeon-nhn** [comment]
@Roksan4614 안녕하세요.

답변이 늦어져 죄송합니다.
현재도 동일한 현상이 발생하시는지요?
이슈 해결을 위해 조금 더 상세한 정보가 필요할 것 같습니다.
사용하시는 유니티/안드로이드 버전과 해당 현상이 일어났을 때, 저희가 확인할 수 있는 로그를 전달해 주실 수 있을까요?

감사합니다.

**Comment by taehyeon-nhn** [comment]
@Roksan4614 안녕하세요.
GPM을 이용해주셔서 감사합니다.

전달 주신 오류 사항이 해결되셨는지 궁금합니다.
동일한 현상이 발생하거나 다른 문의 사항이 있으신 경우 언제든지 편하게 문의 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
@Roksan4614 안녕하세요.

추가 문의가 없어 이슈 클로즈합니다.
다른 문의 사항이 있으시면 언제든 편하게 문의 부탁드립니다.

감사합니다.
