### ISSUE TITLE
XmlHelper의 LoadXmlFromFile 메서드에서 잠재적인 파일 접근 권한 문제로 모듈이 활성화되지 않을 수 있음.

### ISSUE THREAD

**Issue by IJEMIN** [nhn/gpm.unity#184]
## Service

* [ ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST
* [x] Common 

## Version
2.0.5

## Describe the bug
버전관리 프로그램으로 퍼포스를 사용하는 프로젝트에서 GPM의 AssetManagement 모듈을 설치하거나 활성화하는 과정에서 언어 관련 Xml 파일을 읽을때 권한 없음 에러가 일어나 AssetManagement가 활성화되지 않습니다.

XmlHelper.cs의 LoadXmlFromFile() 메서드에서 파일 접근 권한을 FileAccess.Read로 명시적으로 지정하면 정상 동작합니다.

**수정전**

```
            try
            {
                var serializer = new XmlSerializer(typeof(T));
                using (var stream = new FileStream(path, FileMode.Open))
                {
                    result = (T)serializer.Deserialize(stream);
                }
            }
```

**수정후**

```
            try
            {
                var serializer = new XmlSerializer(typeof(T));
                using (var stream = new FileStream(path, FileMode.Open, FileAccess.Read))
                {
                    result = (T)serializer.Deserialize(stream);
                }
            }
```
## To Reproduce
퍼포스 등 체크아웃 전에는 파일을 쓰기 금지로 지정하는 버전 관리 시스템을 활성화하는 프로젝트에서..

1. 유니티 상단 메뉴 Tools > GPM > AssetManagement > Enable

## Expected behavior
AssetManagement 가 예외나 에러 없이 활성화됨

## Environment

- Unity 2020.3.19f1
- Perforce P4V

### Desktop (please complete the following information):
 - OS: Window 10

**Comment by SangYun-nhn** [comment]
@IJEMIN 
제보 주셔서 감사합니다 :)

**Comment by smflt-nhn** [comment]
적용했습니다.
