### ISSUE TITLE
GPM Webview URL UTF-8 문제

### ISSUE THREAD

**Issue by Hoongcha** [nhn/gpm.unity#186]
현재 url에 한글이 들어가면 GPMwebview에서 에러를 뱉고 있는데 혹시 해결 방법이 있을까요? [IOS]

**Comment by taehyeon-nhn** [comment]
@Hoongcha 안녕하세요.
먼저 GPM에 관심 가져주시고 사용해 주셔서 감사드립니다.

WebView iOS에서 한글 Url에 대한 이슈 발생을 제보해 주셔서 감사합니다.
iOS에서 발생하는 이슈 발생의 원인을 확인하였으며, 수정이 완료된 이후 피드백 드리겠습니다.

앞으로도 많은 관심 부탁 드리겠습니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
@Hoongcha 안녕하세요.

iOS에서 발생하는 한글 Url에 대한 이슈 수정해 반영하였습니다.
[Release Notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#141) 참고 부탁드립니다.
Unity Editor/Tools/GPM/Manager 의 목록에서 WebView 업데이트 부탁드립니다.

앞으로도 많은 관심 부탁 드리겠습니다.

감사합니다.
