### ISSUE TITLE
안녕하세요 기능 관련 문의드립니다.

### ISSUE THREAD

**Issue by kawaiipss** [nhn/gpm.unity#193]
안녕하세요 GPM의 Webview를 사용하여 유니티 내에서 구글 설문을 연동하려 합니다.

제공해주신 샘플 씬을 안드로이드 폰(안드로이드 버전: 12, 기종: 갤럭시 S21)에 빌드 하여

미리 제작된 구글설문의 링크를 입력하여 웹뷰 창을 띄웠더니 제대로 표시가 되지 않습니다.

응답자는 구글에 로그인 하지 않은 상태에서 링크만 받아 웹뷰로 구글 설문 응답을 진행하도록 하려고 합니다.

혹시 해결 방법이 없을까요?

**Comment by taehyeon-nhn** [comment]
@kawaiipss 안녕하세요.

GPM을 이용해주셔서 감사합니다.

이슈 확인을 위해 조금 더 자세한 정보가 필요하여 아래 내용에 대한 확인을 부탁드립니다.

1. ShowUrl 호출 시 전달한 파라미터 정보
2. 유니티 버전
3. Android Min SDK 버전, Target SDK 버전
4. 해당 현상이 발생했을 때의 디바이스 로그가 있으시면 로그 첨부 부탁드립니다.

감사합니다.

**Comment by kawaiipss** [comment]
1. ShowUrl 호출 시에는 첫 번째 파라미터로 Unity의 Inputfield.text값을 전달하였습니다.
2. 테스트에 쓰인 유니티 버전은 2021.2.15f1 입니다.
3. Min Android버전은 5.1, Target Sdk버전은 Automatic입니다.
4. 디바이스 로그는 없습니다.

감사합니다

**Comment by taehyeon-nhn** [comment]
@kawaiipss 안녕하세요.

구글 설문지를 작성하여 Inputfield.text로 값을 전달해 확인해보았을 때,
WebView에서 정상적으로 설문지가 로드되었습니다.

추가적으로 아래 설정을 확인해 보시면 좋을 것 같습니다.
* 실제 WebView에 전달하는 URL
* URL의 encoding 여부(WebView 내부에서 URL encoding을 진행하므로 encoding없이 전달해야 합니다.)
* android:networkSecurityConfig 설정
* targetSandboxVersion 설정값

모든 설정이 정상임에도 동일한 현상이 발생하면 아래 내용에 대한 확인과 함께 재문의 부탁드립니다.
1. AndroidManifest.xml 파일의 설정
2. 해당 현상이 발생했을 때의 Logcat 로그(Logcat 로그는 AndroidStudio 의 하단 메뉴에서 확인 가능합니다.)

감사합니다

**Comment by taehyeon-nhn** [comment]
@kawaiipss 안녕하세요.
GPM을 이용해주셔서 감사합니다.

저희가 전달드린 내용으로 문의 사항이 해결되셨는지 궁금합니다.
동일한 현상이 발생하거나 다른 문의 사항이 있으신 경우 언제든지 편하게 문의 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
@kawaiipss 안녕하세요.

추가 문의가 없어 이슈 클로즈합니다.
다른 문의 사항이 있으시면 언제든 편하게 문의 부탁드립니다.

감사합니다.
