### ISSUE TITLE
WebView 사용 중인데 http 로 시작하는 url 접속은 불가능한가요?

### ISSUE THREAD

**Issue by tohinata** [nhn/gpm.unity#194]
sample 씬에서 sample url 을 https://naver.com 으로 설정했는데

모바일에서 확인을 하면

![image](https://user-images.githubusercontent.com/20883553/162110664-9f973d7a-ac6f-4995-8a96-30c391b208de.png)

이렇게 http 로 바뀐 주소로 접속을 해서 웹 로드 실패가 뜹니다.

구글에서는 AndroidManifest.xml 파일에 android:usesCleartextTraffic="true"

추가하라는 내용이 있는데 Android 9 시절 내용이라 무용지물인거 같아요.

유니티 버전 : 2020.3.29f1
Android Gradle 설정 (커스텀) : 6.1.1

**Comment by taehyeon-nhn** [comment]
@tohinata 안녕하세요.

먼저 GPM을 이용해주셔서 감사합니다.

Unity 2020.3에서 https://www.naver.com 및 http://www.naver.com 페이지 정상 접속됨을 확인했습니다.
http로 접속을 시도할 때는 AndroidManifest.xml 파일에 아래 내용을 추가했습니다.
`<application android:usesCleartextTraffic="true">`

추가적으로 아래 설정을 확인해 보시면 좋을 것 같습니다.
* 실제 WebView에 전달하는 URL
* android:networkSecurityConfig 설정
* targetSandboxVersion 설정값

모든 설정이 정상임에도 동일한 현상이 발생하면 아래 내용에 대한 확인과 함께 재문의 부탁드립니다.
1. GpmWebView.ShowUrl 에 전달되는 url
2. Android Min SDK 버전, Target SDK 버전
3. AndroidManifest.xml 파일의 설정
4. 해당 현상이 발생했을 때의 Logcat 로그(Logcat 로그는 AndroidStudio 의 하단 메뉴에서 확인 가능합니다.)

감사합니다.

**Comment by tohinata** [comment]
답변 감사드립니다. Androidmanifest.xml 에 android:usesCleartextTraffic="true" 문구 추가를 했는데도 접속이 안됐었는데,
알고 보니 android:usesCleartextTraffic="true" 문구 추가를 제가 잘 못 한 거였더군요.;
유니티를 배운지 얼마 안된터라...ㅜㅜ


잘못한 편집
<application>
android:usesCleartextTraffic="true"
~~~
~~~
</application>


올바른 편집
<application  android:usesCleartextTraffic="true">
~~~
~~~
</application>

http 주소도 매우 잘 됩니다~!!! 감사합니다~ 따봉~!

**Comment by taehyeon-nhn** [comment]
@tohinata 안녕하세요.

잘 해결되어 다행입니다.
이슈 클로즈하겠습니다.

감사합니다.
