### ISSUE TITLE
Web view multiple screen?

### ISSUE THREAD

**Issue by ramazangolbas** [nhn/gpm.unity#195]
Hello,

Is there any way to make multiple screen in application? I tried different viewers but all of them supporting just one screen at same time.
Are you planning to make multiple screen pop-ups or multiple screen tabs? 

Thanks...

**Comment by taehyeon-nhn** [comment]
Hello. @ramazangolbas 
Thank you for using GPM.

Currently, Multiple screens are not supported.
Multiple screen pop-ups will be supported
Multiple screen tabs do not have a support plan yet.

Please refer to the link for further development details.
[GPM WebView Specifications](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.en.md#specifications)

Thanks.

**Comment by taehyeon-nhn** [comment]
Hello. @ramazangolbas
Close this issue.

If you have any questions, please feel free to contact us.
Thank you.
