### ISSUE TITLE
안녕하세요 웹뷰를 구글 로그인(Web Rest API 방식)에 사용하려고 합니다. 

### ISSUE THREAD

**Issue by mhkim0720** [nhn/gpm.unity#200]
## Service

* [o ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

GPM 버전 2.0.5 
유니티 2021.2.8f 

## Summary
A clear and concise description of what the question is.

안녕하세요 GPM 웹뷰를 사용해 구글 로그인에 사용하려고 하는데 
구글 로그인 api 를 호출하면 403. disallowed_useragent 오류가 발생합니다. 
해서 관련 자료를 찾아보니 useragent를 다른 것으로 호출하여 해결하는 방법이 있다고 하는데요 
GPM 웹뷰 관련 기능에 useragent를 변경하려면 어떻게 해야 하나요? 

아래처럼 userAgent를 변경하면 403에러가 해결 된다고 합니다. !! 
userAgent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'

현재 웹뷰에서 호출하고 있는 url (google login rest api) 입니다. 
https://toytron2021.cafe24.com/toy-tron/api/oauth/google

[useragent 관련 블로그]
https://nitr0.tistory.com/321

## Screenshots
If applicable, add screenshots to help explain your question.
![구글웹뷰 disallowed_useragent](https://user-images.githubusercontent.com/8485731/165217951-94528b2c-e645-460b-8703-036c3e30043e.png)

**Comment by SangYun-nhn** [comment]
@mhkim0720 
안녕하세요

구글에서 보안 정책으로 인앱 웹뷰를 통한 로그인을 막고 있습니다.
관련 이슈일지 몰라서 코멘트 남겨놓습니다.

관련 기사 : https://www.boannews.com/media/view.asp?idx=78883

구글 로그인 방법
- https://support.google.com/accounts/answer/7675428?hl=ko
- https://developers.google.com/identity/protocols/oauth2/native-app

감사합니다.
cc @taehyeon-nhn

**Comment by mhkim0720** [comment]
안녕하세요 

구글에서 보안 정책으로 막아 놓은 것은 알고 있구요  

아래 링크 내 웹뷰 샘플에는 useragent 를 웹뷰 init 할 때 같이 호출할 수 있게 되어 있는데 
이런 기능이 있는지요? 

https://github.com/gree/unity-webview/blob/f35310531ce6598dba17459d8384eaa36bec2dbc/plugins/WebViewObject.cs#L331

GPM 웹뷰 함수 중에 HtmlString이나 js call 을 이용하면 될 것도 같은데 예제 샘플 제공 해주실 수 있을까요?

**Comment by taehyeon-nhn** [comment]
@mhkim0720 안녕하세요.
GPM을 이용해주셔서 감사합니다.

현재 WebView에서는 useragent를 수정하는 기능을 제공하고 있지 않습니다.
useragent를 지원하는 기능을 추가한 버전을 만들어 코멘트를 통해 공유드리겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by taehyeon-nhn** [comment]
@mhkim0720 안녕하세요.

useragent를 지원하는 기능이 추가된 버전을 아래 zip 파일로 공유드립니다.
전달드린 기능이 추가된 버전은 추후 정식 배포에 포함될 예정입니다. 참고 부탁드립니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
[gpm_webview_v1.5.1.unitypackage.zip](https://github.com/nhn/gpm.unity/files/8578555/gpm_webview_v1.5.1.unitypackage.zip)

**Comment by taehyeon-nhn** [comment]
@mhkim0720 안녕하세요.

위 코멘트에 대한 내용 추가드립니다.
useragent 수정은 GpmWebViewRequest.Configuration 의 userAgentString을 통해 진행됩니다.
참고 부탁드립니다.

```cs
new GpmWebViewRequest.Configuration()
{
    ...
    userAgentString = "Custom User Agent String"
}
```

감사합니다.

**Comment by taehyeon-nhn** [comment]
@mhkim0720 안녕하세요.
GPM을 이용해주셔서 감사합니다.

저희가 전달드린 내용으로 문의 사항이 해결되셨는지 궁금합니다.
동일한 현상이 발생하거나 다른 문의 사항이 있으신 경우 언제든지 편하게 문의 부탁드립니다.

감사합니다.

**Comment by mhkim0720** [comment]
안녕하세요 

제공해주신 브라우저에 agent설정 하는 기능을 추가해도 인앱임베디드 브라우저에서는 구글 sns 가 동작하지 않아서 
다른 방법으로 해결 하였습니다. 
다만 원래 뜨던 에러 코드 페이지에서는 한 단계 더 진행되고 다음 페이지에서 다른 에러 코드가 발생합니다. 


감사합니다.

**Comment by taehyeon-nhn** [comment]
@mhkim0720 안녕하세요.

오류 코드가 발생하는 상황을 저희가 재현해 볼 수 있을까요?
Unity 버전, Android Target SDK 및 필수 설정 정보 등의 내용과 오류 상황 및 로그 메시지 등의
내용을 전달해 주신다면 저희가 확인할 수 있는 부분에 대해 확인해 보겠습니다.

감사합니다.

**Comment by mhkim0720** [comment]
@taehyeon-nhn 안녕하세요 
관련 정보를 전달해 드릴 수는 있으나 인앱임베디드 브라우저에서 구글 SNS 로그인은 구글에서 보안 상의 이유로 막아 놓은 걸로 
알고 있는데 이걸 재현할 필요가 있을 까요 ?

**Comment by taehyeon-nhn** [comment]
@mhkim0720 안녕하세요.

전달주신 댓글 내용에 대해 오해한 부분이 있었던 것 같습니다.
다른 방법으로 해결하신 후에도 다른 오류 코드가 나온다고 생각했습니다.

다른 추가 문의 사항이 있으시면 언제든 편하게 문의 부탁드립니다.
감사합니다.

**Comment by taehyeon-nhn** [comment]
@mhkim0720 안녕하세요.

이슈 클로즈하겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 문의 부탁드립니다.
감사합니다.

**Comment by Nautilus0409** [comment]
useragent 수정해서 진행했는데 
![image](https://github.com/nhn/gpm.unity/assets/76603104/7ea9d2ae-27c4-481c-8dc7-bd8446d53e64)

해당 메시지를 얻을 수 있었습니다. 방법이있을까요?
