### ISSUE TITLE
IOS xcode build시 오류 해결방법을 알려주세요

### ISSUE THREAD

**Issue by yuk121** [nhn/gpm.unity#202]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
GPM WebView 1.5.0

## Summary
Unity에서 빌드 후 Xcode에서 빌드(Archive)하면 

The linked framework 'GamePackageManagerWebView.framework' is missing one or more architectures 
required by this target: armv7.

라는 오류 메세지가 뜹니다. 그래서 터미널로 프레임 워크를 확인해본 결과 해당 프레임 워크는 arm64, x86_64에서만 지원하는것을 확인했습니다.
Xcode 빌드 세팅시 기본 아키텍쳐를 armv7, arm64로 사용중인데 이런 경우는 어떻게 해결해야하나요? 
참고로 Excluded Architectures 항목에서 Debug에 Any SDK armv7 을 추가해봤지만 오류는 여전했습니다.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by yuk121** [comment]
자답입니다 . 프로젝트의 Build Setting > Deployment 항목에서 IOS Deployment Target 버전을 10.0 -> 11.0으로 올리니 해결됬습니다

**Comment by taehyeon-nhn** [comment]
@yuk121 안녕하세요.
GPM을 이용해주셔서 감사합니다.

빠르게 해결되어 다행입니다. 답변 주신 것도 감사합니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
