### ISSUE TITLE
Error Gradle Apk

### ISSUE THREAD

**Issue by Luqmanstudio** [nhn/gpm.unity#203]
## Service

* [/] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
2020.3.29F1 LTS

## Summary
Issue exporting to apk as follow the tutorials. As try, with my other project unity no issue exporting apk.

## Screenshots
![image](https://user-images.githubusercontent.com/50491740/167532751-26491a5d-e554-4ef5-a5f6-a51278fb8b91.png)

## Additional context
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:16: error: cannot find symbol
public class UnityPlayerActivity extends Activity implements IUnityPlayerLifecycleEvents
                                                             ^
  symbol: class IUnityPlayerLifecycleEvents
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:18: error: cannot find symbol
    protected UnityPlayer mUnityPlayer; // don't change the name of this variable; referenced from native code
              ^
  symbol:   class UnityPlayer
  location: class UnityPlayerActivity
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:41: error: cannot find symbol
        mUnityPlayer = new UnityPlayer(this, this);
                           ^
  symbol:   class UnityPlayer
  location: class UnityPlayerActivity
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:47: error: method does not override or implement a method from a supertype
    @Override public void onUnityPlayerUnloaded() {
    ^
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:52: error: method does not override or implement a method from a supertype
    @Override public void onUnityPlayerQuitted() {
    ^
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:80: error: cannot find symbol
        if (!MultiWindowSupport.getAllowResizableWindow(this))
             ^
  symbol:   variable MultiWindowSupport
  location: class UnityPlayerActivity
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:90: error: cannot find symbol
        if (!MultiWindowSupport.getAllowResizableWindow(this))
             ^
  symbol:   variable MultiWindowSupport
  location: class UnityPlayerActivity
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:101: error: cannot find symbol
        if (MultiWindowSupport.getAllowResizableWindow(this))
            ^
  symbol:   variable MultiWindowSupport
  location: class UnityPlayerActivity
C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java:112: error: cannot find symbol
        if (MultiWindowSupport.getAllowResizableWindow(this))
            ^
  symbol:   variable MultiWindowSupport
  location: class UnityPlayerActivity
Note: C:\Users\luqman.abdullah_ln\TEST_Error\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:generateReleaseResources
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :launcher:javaPreCompileRelease
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:extractDeepLinksRelease
> Task :launcher:prepareLintJar
> Task :launcher:desugarReleaseFileDependencies
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:parseReleaseLocalResources
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:mergeReleaseShaders
> Task :launcher:mergeReleaseShaders
> Task :unityLibrary:javaPreCompileRelease
> Task :launcher:compileReleaseShaders NO-SOURCE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:collectReleaseDependencies
> Task :launcher:sdkReleaseDependencyData
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:validateSigningRelease
> Task :launcher:mergeReleaseResources
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease NO-SOURCE
> Task :launcher:mergeReleaseAssets
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:compileReleaseLibraryResources
> Task :launcher:processReleaseManifest
> Task :unityLibrary:mergeReleaseNativeLibs
> Task :launcher:mergeReleaseJavaResource
> Task :unityLibrary:stripReleaseDebugSymbols
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:generateReleaseRFile
> Task :launcher:processReleaseResources
> Task :launcher:mergeReleaseNativeLibs
> Task :launcher:stripReleaseDebugSymbols
> Task :launcher:mergeExtDexRelease

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :unityLibrary:compileReleaseJavaWithJavac FAILED
38 actionable tasks: 38 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <7ebb9dc74040436998557fc331a964ba>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by taehyeon-nhn** [comment]
Hello. @Luqmanstudio 
Thank you for using GPM.

It seems to have been updated to Android SDK 30.
Please exit Unity editor and remove the Assets/Library folder and rebuild it.

How to update Android SDK 30.
Run command prompt as an Administrator.
cd "C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\bin"
sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.2"

If you have any questions, please feel free to contact us.
Thanks.

**Comment by Luqmanstudio** [comment]
@taehyeon-nhn 

Can I check does this able to embed local HTML files from the project? If yes, may I know what are the steps to embed the link to a local HTML files?

Thanks

> Hello. @Luqmanstudio Thank you for using GPM.
> 
> It seems to have been updated to Android SDK 30. Please exit Unity editor and remove the Assets/Library folder and rebuild it.
> 
> How to update Android SDK 30. Run command prompt as an Administrator. cd "C:\Program Files\Unity\Hub\Editor\2020.3.29f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\bin" sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.2"
> 
> If you have any questions, please feel free to contact us. Thanks.

**Comment by taehyeon-nhn** [comment]
Hello. @Luqmanstudio 

When you insert an HTML file into the "Your Project/Assets/StreamingAssets" folder, it is included when you build it.
Please check the [document](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#showhtmlfile).
The path is as follows:
* Android
  * string path = "file:///android_asset/some.html";
* iOS
  * string path = "file://" + Application.streamingAssetsPath + "/some.html";

Thanks.

**Comment by ChetanBaraiya** [comment]
![Screenshot 2022-06-13 123113](https://user-images.githubusercontent.com/66196054/173297737-145422ee-c392-4e02-bc9f-c1c493916342.png)

**Comment by taehyeon-nhn** [comment]
Hello. @ChetanBaraiya 

We will test and comment on the dependence on duplicated libraries.
Please add comments if there was anything else special.

Thanks.

**Comment by ChetanBaraiya** [comment]
@taehyeon-nhn  Thank you for your response

When I import the plugin and then build the Apk then it gives the Gradle error.

Thank you

**Comment by taehyeon-nhn** [comment]
Hello. @ChetanBaraiya 

The Unity editor requires an Android SDK 30 update.
Please exit Unity editor and remove the Assets/Library folder and rebuild it.

* How to update Android SDK 30.
1. Run command prompt as an Administrator.
2. cd "C:\Program Files\Unity\Hub\Editor\2020.3.19f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\bin"
3. sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.2"

Thanks.

**Comment by taehyeon-nhn** [comment]
Hello. @ChetanBaraiya 

I wonder if your problem has been solved.
If you have any questions, please feel free to contact us.

Thank you.

**Comment by ChetanBaraiya** [comment]
Hii
Yes, it's solved

Thank you
Chetan baraiya

**Comment by taehyeon-nhn** [comment]
Thank you for your reply.
I will close the issue.
