### ISSUE TITLE
Unity 에서 iOS용으로 개발 시, 단말에서 실행하면 네비게이션 영역이 깨져보입니다.

### ISSUE THREAD

**Issue by t2sleep** [nhn/gpm.unity#209]
## Service

* [ O] WebView

## Version
Unity Gpm WebView 1.3.2

## Describe the bug
안드로이드로 빌드 및 실행할 땐 문제가 없는데, iOS에서 실행하면 사진과 같이
네비게이션바에 버튼이 안보이고 영역 크기가 이상해 집니다.
닫기 버튼 있어야할 자리를 클릭하면 닫기가 되기는 합니다.

## Screenshots
![image](https://user-images.githubusercontent.com/80087086/169047001-fba67b19-da97-4faa-92f3-4e3bc299bf05.png)

### Unity
2019.4.17f1

### Smartphone (please complete the following information):
iPhoneXS
iOS v13

## Additional context
호출한 부분 코드 발췌하여 올립니다.
		GpmWebView.ShowUrl(
		 _webNoticeUrl,
		 new GpmWebViewRequest.Configuration()
		 {
			 style = GpmWebViewStyle.FULLSCREEN,
			 isClearCookie = false,
			 isClearCache = false,
			 isNavigationBarVisible = true,
			 navigationBarColor = "#4B96E6",
			 title = HTLocaleTable.GetLocalstring("UI_Notice"),
			 isBackButtonVisible = true,
			 isForwardButtonVisible = true,
#if UNITY_IOS
            contentMode = GpmWebViewContentMode.MOBILE
#elif UNITY_ANDROID
			 supportMultipleWindows = true
#endif
		 },
		 OnOpenCallback,
		 OnCloseCallback,
		 new List<string>()
		 {
			"USER_ CUSTOM_SCHEME"
		 },
		 OnSchemeEvent);

**Comment by SangYun-nhn** [comment]
@t2sleep 
안녕하세요
GPM 사용해 주셔서 감사드립니다.

[가이드](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#gpmwebviewbundle)에서 네비게이션이 보이질 않을 경우 bundle 추가가 필요하다는 내용이 있습니다.
확인 부탁드립니다.

고맙습니다.

**Comment by taehyeon-nhn** [comment]
@t2sleep 안녕하세요.
GPM을 이용해주셔서 감사합니다.

저희가 전달드린 내용으로 문의 사항이 해결되셨는지 궁금합니다.
동일한 현상이 발생하거나 다른 문의 사항이 있으신 경우 언제든지 편하게 문의 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
@t2sleep 안녕하세요.
이슈 클로즈하겠습니다.

추가 문의 사항이 있으신 경우 언제든지 편하게 문의 부탁드립니다.
감사합니다.
