### ISSUE TITLE
Webview Navigation Data to pass through webview to Unity 

### ISSUE THREAD

**Issue by Shurid16** [nhn/gpm.unity#217]
## Service

* [ ] WebView

## Version
v1.7.0

## Development Environment
Unity

## Current Behavior
There is no callbacks where I can get the data from a webview to pass into Unity. 

## Expected Behavior
A callback where I can get webview navigaton dara such as click on a button from webview to Unity

**Comment by taehyeon-nhn** [comment]
Hello. @Shurid16.
Thank you for using GPM.

Thank you for helping to improve the functionality of GPM.
We will comment when callback is added to the next update.

If you have any questions, please feel free to contact us.
Thanks.

**Comment by taehyeon-nhn** [comment]
Hello. @Shurid16.

Added navigation bar callback.
Please check [release notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.en.md#190) and [guide documents](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.en.md#webview).

Thanks.

**Comment by Shurid16** [comment]
Hi GPM community,

Thanks for the fast response. When can I expect the next update?

Regards
Safayet

**Comment by taehyeon-nhn** [comment]
Hello. @Shurid16.

There will be another update within this week.
No other update schedule has been confirmed.

Thank you.
