### ISSUE TITLE
Unity 에디터와 PC 빌드에서의 지원 질문입니다.

### ISSUE THREAD

**Issue by Hwan6371** [nhn/gpm.unity#231]
## Describe the service
먼저 멋진 웹뷰플러그인을 만들어 주셔서 감사합니다.

에디터와 Windows 빌드환경에서의 지원은 혹시 계획이 있으신지?
만약에 지원을 해주신다면 언제쯤 지원이 가능할지 여쭙습니다.

**Comment by taehyeon-nhn** [comment]
@Hwan6371 안녕하세요.

현재 에디터나 Windows 환경에 대한 지원 여부는 기술 검토 중에 있습니다.
때문에 정확한 지원 일정에 대한 답변을 드릴 수 없는 점 양해 부탁드립니다.
추후 지원이 된다면 Release note 또는 가이드 문서를 통해 알려드리겠습니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
@Hwan6371 안녕하세요.
이슈 클로즈하겠습니다.

추가 문의 사항이 있으신 경우 언제든지 편하게 문의 부탁드립니다.
감사합니다.
