### ISSUE TITLE
Quest/Quest2 support

### ISSUE THREAD

**Issue by MustafaKinAkarsu** [nhn/gpm.unity#240]
Hi, I'm using Unity version 2020.3.23 and would like to know if webview supports Quest/Quest 2 development for VR. Thanks in advance.

**Comment by taehyeon-nhn** [comment]
Hello. @MustafaKinAkarsu

Currently, GPM WebView is not supporting for VR.
Please be informed that GPM WebView has established a development direction to allow WebView to be displayed through the Unity Game Object.

If you have any further questions, please feel free to contact us.
Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @MustafaKinAkarsu
Close this issue.
Please check the [release notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.en.md#release-notes) for future improvements.

If you have any questions, please feel free to contact us.
Thank you.
