### ISSUE TITLE
안녕하세요 Shader기능들을 UI 혹은 특정 카메라 타겟 레이어 대상으로 설정 가능한가요

### ISSUE THREAD

**Issue by lumiereent** [nhn/gpm.unity#256]
## Describe the service
샘플 기능과 코드를 살펴 보니 지금은 단일 Texture 대상으로만 기능이 적용되는것 같습니다.
Dissolve, Grayscale, Sepia 등은 보이는 화면전체에 연출용으로 사용할 일이 많다고 여겨집니다.

## Additional context
Canvas하위의 UI 이미지 전체나, 특정 카메라에 렌더링되는 레이어를 대상으로, 해당 섀이더 기능들을 적용 가능할까요?

**Comment by taehyeon-nhn** [comment]
@lumiereent 안녕하세요.

Shader를 특정 Camera에 적용하기 위해 script 파일에 OnRenderImage 함수를 구현하고,
shader를 적용한 material을 OnRenderImage에서 사용하여 효과를 표현할 수 있습니다.
Script 파일이 Camera의 component로 추가되어야 합니다.
```
private Material material;
private void OnRenderImage(RenderTexture source, RenderTexture destination)
{
    if (material)
    {
        Graphics.Blit(source, destination, material, 0);
    }
}
```

Dissolve, Grayscale, Sepia 등의 셰이더를 Camera를 통해 표현하는 효과의 추가에 대해 개발 검토하겠습니다.
추후 가이드 문서나 ReleaseNotes를 참고 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
@lumiereent 안녕하세요.

결과 공유 감사합니다.
이슈 클로즈하겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
