### ISSUE TITLE
Webview/ 유니티에서 웹뷰를 UI 부분이나 Texture 기능을 업데이트 하실 예정이신가요?

### ISSUE THREAD

**Issue by windyflowsSunburn** [nhn/gpm.unity#257]
## Service

* [x] WebView

## Version
Lasted Version

## Summary
Webview Feature Question 

## Screenshots
None

## Additional context

Asset을 잘사용하고 있습니다. 혹시나 웹뷰를 HTML Texture나 Texture 변환하여 UI 부분이나 맵핑처리가 가능한지 알고싶습니다.
현재 버전에서 안된다면 업데이트할 예정인지 알고 싶습니다. 감사해요~

**Comment by taehyeon-nhn** [comment]
@windyflowsSunburn 안녕하세요.
먼저 GPM을 이용해 주셔서 감사합니다.

문의 주신 Texture 변환에 대한 기능을 개발 예정입니다.
정확한 일정은 전달드리기 어려운 점, 양해 부탁드립니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by taehyeon-nhn** [comment]
@windyflowsSunburn 안녕하세요.
이슈 클로즈하겠습니다.
추후 개선 사항은 [릴리즈 노트](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#release-notes)를 통해 확인 부탁드립니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
