### ISSUE TITLE
[Webview] error: AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by GALICSOFT** [nhn/gpm.unity#258]
Hi,
I walk for Netmarble N2 Technical Support Team.
I have got an error while reviewing the GPM, and would like some help.
## Service

* [ ] WebView

## Version
* [GPM: 2.1.0](https://assetstore.unity.com/packages/tools/utilities/game-package-manager-147711#publisher)
* Unity: 2021.3.5f1
* Target: <img src="https://user-images.githubusercontent.com/9015539/179432836-1e855297-7cb9-4c43-868e-eddfea457ce1.png" width="600" />

## Summary
* just build the Assets\GPM\Assets\GPM\WebView\Sample\Sample.unity  and get a error.
* I traced the code and find the error occured at the code 
```
		public void CallAsync(string domain, string data, string extra) {
            jc.CallStatic("onRequestAsync", domain, data, extra);
        }
```
* E/Unity(10490): AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	E/Unity(10490): java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	E/Unity(10490): at com.gpm.webview.GpmWebViewConfiguration$Builder.style(GpmWebViewConfiguration.kt)
	E/Unity(10490): at com.gpm.webviewplugin.GpmWebViewPlugin.getConfiguration(GpmWebViewPlugin.java:581)
	E/Unity(10490): at com.gpm.webviewplugin.GpmWebViewPlugin.showUrl(GpmWebViewPlugin.java:452)
	E/Unity(10490): at com.gpm.webviewplugin.GpmWebViewPlugin.onAsyncMessage(GpmWebViewPlugin.java:210)
	E/Unity(10490): at com.gpm.webviewplugin.GpmWebViewPlugin$1.onRequestMessageAsync(GpmWebViewPlugin.java:147)
	E/Unity(10490): at com.gpm.communicator.internal.MessageReceiver.onRequestAsync(MessageReceiver.java:45)
	E/Unity(10490): at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	E/Unity(10490): at com.unity3d.player.UnityPlayer.access$300(Unknown Source)
	E/Unity(10490): at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
	E/Unity(10490): at android.os.Handler.dispatchMessage(Handler.java:98)
	E/Unity(10490): at android.os.Looper.loop(Looper.java:154)
	E/Unity(10490): at com.unity
	D/WifiNative-HAL(2166): Failing getSupportedFeatureset because HAL isn't started
	E/BatteryStatsService(2166): no controller energy info supplied
	E/BatteryStatsService(2166): no controller energy info supplied
	E/KernelCpuSpeedReader(2166): Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
	E/KernelUidCpuTimeReader(2166): Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
	E/BatteryStatsService(2166): modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}

## Screenshots
* <img src="https://user-images.githubusercontent.com/9015539/179432244-aabbd6fa-a72e-4232-9570-2dedf9309645.png" width="800" />
* <img src="https://user-images.githubusercontent.com/9015539/179432554-3b988582-bb63-49e7-963d-2c9a1cffc4fc.png" width="800" />

**Comment by taehyeon-nhn** [comment]
Hello. @GALICSOFT.
Thank you for using GPM.

Please check the Kotlin dependence in the mainTemplate.gradle file.
Please refer to the [GPM WebView Android setting](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.en.md#android) and reconfirm after adding dependencies.

If you have any questions, please feel free to contact us.
Thank you.

**Comment by GALICSOFT** [comment]
I Add the dependencies as per guide instructions, and resove the problem.
Thank you.
```
dependencies {
    //...
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72'
}
```

**Comment by taehyeon-nhn** [comment]
Thank you for your reply.
I will close the issue.
