### ISSUE TITLE
웹뷰 카메라, 마이크 권한에 대해 문의드립니다.

### ISSUE THREAD

**Issue by jaebul2006** [nhn/gpm.unity#264]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add 
![Screenshot_20220726-152151](https://user-images.githubusercontent.com/20273148/180938857-f130f9ae-0864-4a9c-93bc-d7968e146423.jpg)
screenshots to help explain your question.

## Additional context
웹뷰 카메라, 마이크 권한에 대해 문의드립니다. 개발중인 앱에서 웹뷰를 통해 특정사이트에 접속하고 화상회의 서비스를 진행하야여
하는데요. 스크린샷과 같이 카메라, 마이크 권한이 없어서 제대로 진행되지않습니다. 일반 웹브라우저로 접속시 권한 요청 팝업이
뜨고 수락을 하면 진행이 되지만 웹뷰로 접속했을때는 권한요청 수락창이 뜨질않습니다. 혹시 해결 가능한 방법이 있을까요? 
감사합니다.

**Comment by taehyeon-nhn** [comment]
@jaebul2006 안녕하세요.
먼저 GPM을 이용해 주셔서 감사합니다.

문의하신 권한 요청 관련 기능이 GPM Webview에 추가되지 않아 발생한 현상으로 보입니다.
관련 기능 추가해 댓글로 내용 전달드리겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by taehyeon-nhn** [comment]
@jaebul2006 안녕하세요.

GPM WebView v1.8.0이 업데이트 되었습니다. [Release Notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#180)
Android에서 권한을 추가하면 WebView에서 인식하여 화상 회의 등에 필요한 권한을 허용할 수 있습니다.

Unity에서의 Android 권한 획득의 경우 [런타임 권한 요청](https://docs.unity3d.com/kr/current/Manual/android-RequestingPermissions.html) 문서를 참고 부탁드립니다.
또는 Android plugin을 제작하여 권한을 획득할 수 있습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by taehyeon-nhn** [comment]
@jaebul2006 안녕하세요.
이슈 클로즈하겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
