### ISSUE TITLE
LogViewer 의 로그를 파일로 저장할 수 있습니까?

### ISSUE THREAD

**Issue by Kim-Myung-Sik** [nhn/gpm.unity#272]
## Service

* [ ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ V] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
    로그뷰어의 로그를  메일로 보내지 않고  파일로 저장할 수 있습니까?
    그런 기능이 없다면 추후 업데이트할 계획이 있습니까?

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by smflt-nhn** [comment]
@Kim-Myung-Sik 
안녕하세요. 현재 UI로 파일로 저장하는 기능은 없습니다.

대신 Gpm.LogViewer.Internal 네임스페이스 내의 
Log.Instance.WriteFullLogToFile 함수로 메일에 보내는 파일을 만들 수 있습니다.
저장 경로는 Application.persistentDataPath/GpmLogViewerLogForMail.txt 입니다.

```
Gpm.LogViewer.Internal.Log.Instance.WriteFullLogToFile(exception =>
{
    if (exception == null)
    {
        // 저장
    }
    else
    {
        // 실패
    }
});
```

로그를 파일로 저장하는 것도 유용할 것으로 생각됩니다.

현재 다른 프로젝트 작업으로 일정을 구체적으로 말씀드리기 어렵습니다만 적극 검토해 보겠습니다.

기능이 추가된 이후 피드백 드리겠습니다. 앞으로도 많은 관심 부탁 드리겠습니다.

감사합니다.

**Comment by smflt-nhn** [comment]
@Kim-Myung-Sik

안녕하세요.
로그뷰어 2.1.0에 기능 추가되어 배포되었습니다.

![image](https://github.com/user-attachments/assets/31693a18-5c6b-4873-9065-faf2e55964af)
