### ISSUE TITLE
WebView 켜진 상태에서 유니티 UI 클릭이 가능한 방법이 있을까요?

### ISSUE THREAD

**Issue by KHS-baechu** [nhn/gpm.unity#273]
## Service

* [ 0 ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Unity 2020.3.26f1
GPM WebView 1.8.1

## Summary
안녕하세요
저같은 초보 개발자를 위해 웹뷰를 만들어 주셔서 감사합니다.

다름이 아니라 웹뷰가 켜진 상태에서는 유니티 상의 버튼들은 클릭하는 방법이 있을까요?
찾아보고 매뉴얼 정독을 해봤지만 기능을 찾지 못해서 혹시 제가 모르는 것이 있나 여쭤봅니다.

## Screenshots
![Screenshot_20220825-122519_GPM_Test](https://user-images.githubusercontent.com/100125520/186569603-28831422-feb5-4e0e-b01d-ba2a8ea42507.jpg)

**Comment by taehyeon-nhn** [comment]
안녕하세요. @KHS-baechu님.
먼저 GPM을 사용해 주셔서 감사합니다.

현재는 해당 기능을 지원하지 않고 있습니다.
GPM WebView는 Unity Game Object를 통해 WebView를 표시할 수 있도록 개발 방향을 정해두고 있습니다.
추후 업데이트되면  [가이드 문서](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#%EC%8A%A4%ED%8E%99)를 통해 확인 부탁드립니다.

감사합니다.

**Comment by KHS-baechu** [comment]
감사합니다 좋은하루되세요

**Comment by taehyeon-nhn** [comment]
이슈 클로즈하겠습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
