### ISSUE TITLE
The plug-in has just been installed and the following error appears；“The Unity version is not supported.”

### ISSUE THREAD

**Issue by XuSummer** [nhn/gpm.unity#279]
## Service

* [ ] Manager Page

## Version
2.2.0
## Unity Version
2021.3.8f1c1

## Describe the bug
The plug-in has just been installed and the following message appears
"The Unity version is not supported."
error on console:
FormatException: Input string was not in a correct format.
System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) (at <c2a97e0383e8404c9fc0ae19d58f57f1>:0)
System.Number.ParseInt32 (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) (at <c2a97e0383e8404c9fc0ae19d58f57f1>:0)
System.Int32.Parse (System.String s) (at <c2a97e0383e8404c9fc0ae19d58f57f1>:0)
Gpm.Manager.Util.StringUtil+UnityVersion..ctor (System.String version) (at Assets/GPM/Manager/Editor/Util/StringUtil.cs:54)
Gpm.Manager.Util.StringUtil.IsInstallableUnityVersion (System.String compareVersion) (at Assets/GPM/Manager/Editor/Util/StringUtil.cs:19)
Gpm.Manager.Ui.GpmServiceDetail.<LoadService>b__18_0 (Gpm.Manager.Constant.ServiceInfo info, Gpm.Manager.Constant.ManagerError error) (at Assets/GPM/Manager/Editor/UI/GpmServiceDetail.cs:60)
Gpm.Manager.Internal.GpmManager+<>c__DisplayClass59_0.<LoadServiceInfo>b__0 (Gpm.Manager.Constant.ServiceInfo result, Gpm.Manager.Constant.ManagerError error) (at Assets/GPM/Manager/Editor/Internal/GpmManager.cs:261)
Gpm.Manager.Internal.GpmManager+<>c__DisplayClass60_0.<RequestServiceInfo>b__0 (Gpm.Manager.Constant.ServiceInfo info, Gpm.Manager.Constant.ManagerError error) (at Assets/GPM/Manager/Editor/Internal/GpmManager.cs:278)
Gpm.Manager.Internal.GpmManager+<>c__DisplayClass60_1.<RequestServiceInfo>b__3 (Gpm.Common.Multilanguage.MultilanguageResultCode result, System.String resultMessage) (at Assets/GPM/Manager/Editor/Internal/GpmManager.cs:349)
Gpm.Common.Multilanguage.Internal.MultilanguageImplementation+<>c__DisplayClass6_0.<Load>b__0 (Gpm.Common.Multilanguage.MultilanguageResultCode resultCode, Gpm.Common.Multilanguage.Internal.MultilanguageXml xmlData, System.String messageInfo) (at Assets/GPM/Common/Multilanguage/Internal/MultilanguageImplementation.cs:45)
Gpm.Common.Multilanguage.Internal.MultilanguageLoader+<>c__DisplayClass7_0.<LoadDownloadFile>b__1 (Gpm.Common.Util.XmlHelper+ResponseCode xmlResultCode, Gpm.Common.Multilanguage.Internal.MultilanguageXml xmlData, System.String xmlResultMessage) (at Assets/GPM/Common/Multilanguage/Internal/MultilanguageLoader.cs:159)
Gpm.Common.Util.XmlHelper.LoadXmlFromText[T] (System.String text, System.Action`3[T1,T2,T3] callback) (at Assets/GPM/Common/Util/XmlHelper.cs:115)
Gpm.Common.Multilanguage.Internal.MultilanguageLoader+<>c__DisplayClass7_0.<LoadDownloadFile>b__0 (Gpm.Common.Multilanguage.MultilanguageResultCode result, System.String loadText, System.String resultMessage) (at Assets/GPM/Common/Multilanguage/Internal/MultilanguageLoader.cs:155)
Gpm.Common.Multilanguage.Internal.MultilanguageLoader+<DownloadFile>d__8.MoveNext () (at Assets/GPM/Common/Multilanguage/Internal/MultilanguageLoader.cs:223)
Gpm.Common.Util.EditorCoroutine.CheckMoveNext (System.Collections.IEnumerator enumerator) (at Assets/GPM/Common/Util/EditorCoroutine.cs:102)
Gpm.Common.Util.EditorCoroutine.MoveNext () (at Assets/GPM/Common/Util/EditorCoroutine.cs:67)
Gpm.Common.Util.EditorCoroutine.Update () (at Assets/GPM/Common/Util/EditorCoroutine.cs:47)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <5456dbfeccf644f7ab5b4d4a01ccf33e>:0)

## To Reproduce
1. Unity Editor -> "Tools" -> "GPM"  
2. Click any one, It is shown on the right  "The Unity version is not supported."

## Screenshots
![image](https://user-images.githubusercontent.com/20227019/187822749-5ffd7468-f3b1-44db-9c77-b3a1f40806ce.png)

**Comment by smflt-nhn** [comment]
@XuSummer 

Thanks for reporting the bug.
This bug is an error that occurs when c1 is included in the version.
I'll fix it and release it soon. 

I have attached the modified package.
[gpm_manager_v2.2.1.zip](https://github.com/nhn/gpm.unity/files/9468049/gpm_manager_v2.2.1.zip)

Please use it before distribution.
