### ISSUE TITLE
Webview window size

### ISSUE THREAD

**Issue by Bluesky817** [nhn/gpm.unity#280]
## Service

* [ 0 ] WebView

## Version
Write the version that you are currently using.
GPM 2.2.2

## Development Environment
Write the version of Unity, OS and so on.
Unity 2021.3.6f1 , Windows 10

## Current Behavior
Webview 창을 전체창으로 사용하지 않을경우(팝업모드?).
창의 여백의 부분의 클릭이 안됩니다.

## Expected Behavior
팝업창으로 사용할 경우
뒤쪽의 버튼이 눌러지도록 webview 창의 크기 자체를 조절할수 있도록 부탁합니다.
![eclipse-1492818_1920](https://user-images.githubusercontent.com/26814614/188264960-d2ccdb51-ec55-4868-8c7a-2eb1a821c3d4.jpg)

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Bluesky817님.
먼저 GPM을 사용해 주셔서 감사합니다.

현재는 해당 기능을 지원하지 않고 있습니다.
GPM WebView는 Unity Game Object를 통해 WebView를 표시할 수 있도록 개발 방향을 정해두고 있습니다.
추후 업데이트되면 [가이드 문서](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#%EC%8A%A4%ED%8E%99)를 통해 확인 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Bluesky817님.

WebView v2.0.0이 배포되었습니다.
팝업 영역만 이벤트 처리에 사용되게 수정되었습니다.
GPM WebView의 SampleWebView.cs 파일과 [ReleaseNotes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#200)를 참고 부탁드립니다.

감사합니다.
