### ISSUE TITLE
안녕하세요 WebView사용중 문의 드립니다.

### ISSUE THREAD

**Issue by lumiereent** [nhn/gpm.unity#287]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
2.2.2

## Summary
웹뷰 안의 컨텐츠가 확대되어 보이는 현상

## Screenshots
1-1. GpmWebViewStyle.POPUP으로 웹뷰를 열 경우 (제가 원하는 화면입니다.)
![webview 1](https://user-images.githubusercontent.com/89391503/192961641-55f8bc3e-8f89-4c4a-b891-aa8713ffb274.png)

1-2. 열고나서 1초 뒤 갑자기 내부 컨텐츠가 확대되고 스크롤바가 생기는 현상
![webview 2](https://user-images.githubusercontent.com/89391503/192961663-a810a532-b2fe-46f8-82d1-9a413d080082.png)

2. GpmWebViewStyle.FULLSCREEN 모드로 설정할 경우 원하는 화면은 맞으나, 아래와 같이 제목과 닫는 버튼이 보이지 않음
![캡처3](https://user-images.githubusercontent.com/89391503/192962451-bd849a20-9a0b-48a3-a6df-b2f5c6df66ea.PNG)

## Additional context
갑자기 컨텐츠 사이즈가 확대되는 현상을 어떻게 방지해야 할지 잘 모르겠어서 문의 드립니다.

**Comment by lumiereent** [comment]
return new GpmWebViewRequest.Configuration()
            {
                style = GpmWebViewStyle.POPUP,
                isClearCache = true,
                isClearCookie = true,
                title = "Other Games",

                isNavigationBarVisible = false,
                isBackButtonVisible = false,
                isForwardButtonVisible = false,

                supportMultipleWindows = false,

                contentMode = GpmWebViewContentMode.RECOMMENDED,
                isMaskViewVisible = false
            };

해당 Configuration 설정에서 3번은 style만 바꿨습니다.

**Comment by lumiereent** [comment]
몇가지 추가로 테스트해보고 있습니다.isNavigationBarVisible 등의 bool 옵션들을 모두 true해보니 2번 이슈인 풀스크린에서도 타이틀은 보입니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @lumiereent 님.

조금 더 정확한 확인을 위해 아래 내용 전달 부탁드립니다
* Unity 버전
* GPM WebView 버전
* 모바일 디바이스 종류
* 모바일 OS 버전

해당 현상의 경우 html 페이지의 meta tag 설정으로 인해 화면이 변경되어 보일 수 있을 것 같습니다.
해당 페이지의 URL에 저희가 접근할 수 있을지도 확인 부탁드립니다.

감사합니다.

**Comment by lumiereent** [comment]
https://www.lumiere-entertainment.com/bott 이며 wix를 통해 사이트를 제작하고 있습니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @lumiereent 님.

전달해 주신 웹페이지의 경우 모바일 디바이스 전체 width 미만의 WebView에서 페이지가 확대되는 현상이 발생하고 있습니다.
해당 웹페이지(https://www.lumiere-...)에 대해 GPM WebView 및 타사 WebView로 테스트해보았을 때, 동일한 현상이 발생했습니다.
다른 웹페이지의 경우 GPM WebView 및 타사 WebView에서 팝업 형태 및 전체 화면에서 정상 노출되는 점을 확인했을 때,
WebView 자체의 이슈라기보다 Wix에서 제공하는 에디터의 내부 설정(모바일 설정 등)을 통해 제어가 필요한 것으로 보입니다.

수정이나 추가가 필요한 기능이 있으시면 내용 전달 부탁드립니다.
감사합니다.

**Comment by lumiereent** [comment]
답변 감사합니다! 해결방법이 있는지 에디터 설정을 통해 찾아보도록 하겠습니다

**Comment by lumiereent** [comment]
안녕하세요 iOS Fullscreen 모드 웹뷰에서 추가적인 문의를 드리고자 합니다.

iOS에서는 같은 설정이라도 웹뷰 상단에 Close버튼이 나오지 않는 듯 해서
Close버튼을 어떻게 띄워야 하는지 문의 드립니다.
아래 설명란에도 내용이 비어 있어서 첨부합니다.

![캡처](https://user-images.githubusercontent.com/89391503/194235516-2a0f3cf2-6d41-4334-bc16-9e1461e4314a.PNG)

**Comment by taehyeon-nhn** [comment]
안녕하세요. @lumiereent 님.

Parameter 옵션의 경우 GpmWebViewStyle.POPUP을 대상으로 Close 버튼의 On/Off를 제어할 수 있다는 내용입니다.
iOS에서 버튼의 이미지가 나오지 않는 경우 [GPMWebView.bundle 파일의 추가](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#gpmwebviewbundle) 부탁드립니다.
bundle이 추가가 된 상태라면 Popup Configuration의 옵션을 다시 한 번 확인 부탁드립니다.

감사합니다.

**Comment by lumiereent** [comment]
아 추가하니 잘 나옵니다!!

제가 아래 형태로 시작하는 유니티 PostProcessBuild 코드를 사용하고 있습니다.
            string projPath = pathToBuiltProject + "/Unity-iPhone.xcodeproj/project.pbxproj";

            UnityEditor.iOS.Xcode.PBXProject proj = new UnityEditor.iOS.Xcode.PBXProject();
            proj.ReadFromString(File.ReadAllText(projPath));

혹시 유니티에서 미리 설정가능한 GPMWebView.bundle 파일을 추가하는 로직이 샘플이 있을까요?

**Comment by taehyeon-nhn** [comment]
안녕하세요. @lumiereent 님.

GPM WebView의 경우 bundle 파일의 유무를 확인하는 작업이 우선되어야 해서 bundle 파일의 자동 추가는 지원하지 않고 있습니다.
아래 forum 링크가 도움이 되실지 모르겠습니다.
https://forum.unity.com/threads/add-file-to-xcode-copy-bundle-resources-phase-via-script.913187/

감사합니다.

**Comment by lumiereent** [comment]
감사합니다!

**Comment by cloudy3** [comment]
Hi, may I know how to add a close button on Android?

안녕하세요, Android에서 닫기 버튼을 추가하는 방법을 알 수 있습니까?

**Comment by taehyeon-nhn** [comment]
안녕하세요. @lumiereent 님.
이슈 종료하겠습니다.
추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

Hello. @cloudy3.
Please refer to the [issue 295](https://github.com/nhn/gpm.unity/issues/295).
Thank you.

**Comment by lumiereent** [comment]
안녕하세요 제가 저번에 문의드린 페이지를 만든 도중 iOS 리젝사유 관련이 있어 도움을 얻고자 합니다.


Guideline 2.5.2 - Performance - Software Requirements

During review, your app installed or launched executable code, which is not permitted on the App Store. Specifically, your app uses the itms-services URL scheme to install an app.


Please note that while educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code, such code may not be used for other purposes and such apps must make the source code completely viewable and editable by the user.


The next submission of this app may require a longer review time.



제가 웹지식 관련해서 부족한 면이 있어
리젝사유가 의미하는 내용이 무엇인지 추측이 안되서 여기에 문의드리게 되었습니다.

특히 itms-services URL scheme가 무엇을 의미하는지는 잘 모르겠는데
직접적으로 (itms-services://)관련 url을 사용하진 않고 

스토어로 링크되는 버튼을 https://apps.apple.com/app/id{} 이런 url로 이동하도록 하였는데
혹시 웹뷰에서 저 링크를 호출하는것이 itms-services URL을 의미하는 것인가요? 

아니면 웹뷰 기능의 다른곳에서 의심가는 곳이 있을지 궁금합니다.

**Comment by smflt-nhn** [comment]
@lumiereent 
안녕하세요.

리젝으로 급하실것 같은데 현재 담당자가 빠르게 답변이 힘든 관계로 이슈에 대한 내용 전달 드립니다.
https://www.clien.net/service/board/cm_app/17417991
위 링크에서도  https://itunes.apple.com/kr/app/id{}로 호출했고 itms-service 문제로 리젝 받았는데
https://itunes.apple.com에서 itms-app://으로 리디렉션을 해서 문제가 발생한것 같습니다.

감사합니다.

**Comment by lumiereent** [comment]
빠른 답변 감사합니다! 도움이 되었습니다.

**Comment by lumiereent** [comment]
안녕하세요.. 제가 아직까지 위 이슈로 리젝이 되고 있는데
당최 원인을 알 수 없어 뭔가 단서라도 얻을 수 있을까 싶어 글을 남겨 봅니다.

현재 위 가이드라인(Guideline 2.5.2 - Performance - Software Requirements)
을 제외하고는 정확한 리젝 사유도 알려주지 않고 있어서
iOS의 URL Scheme부분이 문제가 되는 것으로 추측하고 있는 상황입니다.

지금현재 GpmWebView.ShowUrl 함수 호출 자체를 안하고 가능성은 낮다고 생각합니다만
샘플코드 예시와 같이 "CUSTOM_SCHEME" 부분을 그대로 두고 있는 상황인데
저는 전혀 사용하고 있진 않지만 저게 무언가 리젝사유에 문제가 될 수도 있을까요
혹은 GpmWebView 프레임워크 내에서 itms-services관련 URL scheme가 추측되는게 있는지 궁금합니다.

자체적으로는 모든 스토어 관련 호출을 없애고 빌드 업데이트를 해 보아도 계속 같은 리젝이라 여기도 문의 드려봅니다.

**Comment by lumiereent** [comment]
Xcode에서 수동으로 GPMWebView.bundle 파일도 추가하고 있습니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @lumiereent 님.

WebView에서 AppStore를 열 수 있도록 추가된 scheme 중 itms-services 에 문제가 있는 점을 확인했습니다.
[Apple 플랫폼 배포](https://support.apple.com/ko-kr/guide/deployment/depce7cefc4d/web)의 `웹 사이트를 사용하여 앱 배포하기`를 참고 부탁드립니다.

GPM WebView v1.9.2 버전에 itms-services 스킴이 제거되어 업데이트되었습니다.
GPM Manager를 통해 업데이트 부탁드립니다.
[Release Notes 1.9.2](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.en.md#192)

감사합니다.

**Comment by lumiereent** [comment]
안녕하세요 수정해 주셔서 감사합니다
itms-services란게 스토어를 여는 기능이란것은 알고 있지만
정확히 어떤 부분의 문제 때문이였는지 
향후 프로젝트 개발에 비슷한 이슈가 생길 경우 참고하고자 합니다.

1. GPM 내부에서 어떠한 경우에 AppStore링크를 여는 기능이 필요하여 스키마를 추가하게 되었나요?

2. 혹여나 타사의 프레임워크에서 itms-services scheme가 포함되어 있는지 없는지 자체적으로 찾아 볼 수 있는 방법이있나요?
(저도 원인을 Xcode내에서 직접 찾아보고자 하였지만 발견하지 못하였습니다.)

**Comment by taehyeon-nhn** [comment]
안녕하세요.

문의에 대한 답변 전달드립니다.
1. GPM WebView 내부에서 itms-apps 등과 같은 스킴을 통해 AppStore를 열기 위해 추가되었습니다.
2. 프레임워크에서 내부 코드를 알 수 없으면 특정 스킴의 사용 및 포함 여부를 확인하기 힘듭니다.

답변이 도움이 되실지 모르겠습니다.
추가로 GPM을 사용한 앱의 이름을 알려주실 수 있는지 확인 부탁드립니다.
향후 GPM의 이슈 확인 및 개선에 도움이 될 것입니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by lumiereent** [comment]
앱이름은 Serendipity; The Mafias 입니다.
