### ISSUE TITLE
intent: 링크에서 net::err_unknown_url_scheme 오류

### ISSUE THREAD

**Issue by bio-metal** [nhn/gpm.unity#288]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
1.9.0

## Summary
웹뷰 내에서 카카오api 서비스를 이용하는데 카카오링크를 누르면 net::err_unknown_url_scheme 오류가 발생.

## Screenshots
아래 티스토리 링크 블로그내에 완전히 똑같은 스크린샷이 존재함으로 아래 링크로 대체합니다

## Additional context
이 문제에 대한 해결법을 검색한 결과
https://bacassf.tistory.com/110
https://blog.naver.com/PostView.naver?blogId=ryus00m&logNo=222446789709
두개의 블로그를 찾았지만
네이티브 소스의 shouldOverrideUrlLoading
 함수를 수정해야하는 방법이라 따라할수가 없는 상태입니다.
intent: 를 제거하는 방법도 카카오 api를 만질수가 없으니 불가능한 상태입니다.
custom schemeList에 kakaolink:// , intent: , intent:kakaolink:// 다 넣어봐도 소용 없는 상태입니다.

개발환경 : 윈도우10, 유니티2020.3.30f1
테스트환경 : 갤럭시S20 안드로이드10, 갤럭시 플립3 안드로이드12

**Comment by taehyeon-nhn** [comment]
안녕하세요. @bio-metal 님.

Android의 shouldOverrideUrlLoading 내부 로직이 수정되어 업데이트되었습니다.
GPM WebView 업데이트 및 [릴리스 노트](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#191) 확인 부탁드립니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by bio-metal** [comment]
업데이트 감사합니다.
다른 일이 바쁘다보니 이제서야 시간이 되었습니다.
그런데 1.9.2로 업데이트 후 실행해보았는데 변한게 없습니다...ㅜㅜ
혹시 제가 따로 처리해줘야하는 부분이 있는건지요?

schemeList 에 아무것도 넣지 않고 테스트도 해보았고
intent: 나 intent:kakaolink:// 를 넣고 테스트해도 기존과 증상이 똑같았습니다.
혹시 제가 설정을 잘못한건지....

**Comment by taehyeon-nhn** [comment]
안녕하세요. @bio-metal 님.

수정된 shouldOverrideUrlLoading 안에서 `intent:`를 검사해 패키지가 있다면 startActivity를 통해 호출하고,
패키지가 없다면 마켓으로 이동합니다.
전달해주신 테스트 페이지는 아래와 같은 메시지가 노출됩니다.
`You don't have permission to access /testkakaolick.php on this server.`

감사합니다.

**Comment by bio-metal** [comment]
죄송합니다. 주소가 https가 아니라 http 였습니다. 링크를 수정하였습니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @bio-metal 님.

테스트 페이지 전달 감사합니다.

GPM WebView Android에서 custom scheme을 등록할 때 Uri.parse를 통해 등록한 점이 문제가 되어 
`intent:kakaolink:` 등의 scheme이 정상 인식되지 않아 Unity로 custom scheme 이벤트가 전달되지 않았습니다.
(iOS에서의 custom scheme 등록은 이슈 없습니다.)
해당 내용은 다른 이슈와 함께 수정되어 12월 9일 업데이트될 예정입니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @bio-metal 님.

GPM WebView 1.10.0 이 릴리스되었습니다.
Android custom scheme 저장에 대한 이슈가 수정되었으며, 전달해 주신 내용의 경우 `intent:kakaolink:` 를 custom scheme으로 등록하신 후 GpmWebView.ShowUrl에 등록한 콜백에서 해당 링크에 대한 처리를 해주시면 됩니다.
[릴리스노트](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#1100) 와 [가이드 문서](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md) 참고 부탁드립니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.
