### ISSUE TITLE
scheme을 호출하는 형식을 전혀 모르겠습니다.

### ISSUE THREAD

**Issue by JungUook** [nhn/gpm.unity#294]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
최신

## Summary
scheme 사용법을 모르겠습니다

## Screenshots
.

## Additional context
개발환경: 유니티 2021.3.10f1, 윈도우 10
테스트환경: 갤럭시S9

웹뷰를 처음 호출할때 custom scheme을 넣으면 콜백을 받을 수 있다고 되어있는데
어떤 형식으로 받아야할지 전혀 모르겠습니다.

보통 카카오나 네이버같은 경우 intent:// 이런 형식으로 되어있던데
gpm webview의 경우 이미 구현된 scheme들이 gpmwebview://scheme 이런 형식으로 되어있더라고요?

그래서 해당형식으로도 호출해봤는데 앱이 그냥 강제종료되어버립니다.

혹시나 샘플신에 custom scheme를 사용한 곳이 있나 찾아봤는데
리스트에 CUSTOM_SCHEME이라고는 되어있는데 정작 사용된 곳은 찾지 못햇습니다.

웹뷰에서 자바스크립트로 custom scheme List에 있는 scheme을 호출할때 어떤 형식으로 호출해야하는지 알려주실 수 있나요?

**Comment by taehyeon-nhn** [comment]
안녕하세요. @JungUook님.
먼저 GPM을 사용해 주셔서 감사합니다.

문의하신 Custom scheme의 경우 웹페이지에 미리 정의되어 있어야 합니다.
간단한 예를 들면, 아래와 같은 웹페이지의 내용이 있을 때,
```html
<html><body>
<a href="something://test">Test Link</a>
</body></html>
```
custom scheme으로 `"something://"`을 사용하실 수 있습니다.

아래와 같이 WebView를 호출했을 때,
```cs
GpmWebView.ShowUrl(sampleUrl, configuration, OnWebViewCallback, "something://");
```
WebView가 열린 이후 `OnWebViewCallback`으로 `GpmWebViewCallback.CallbackType.Scheme`이 전달되며,
parameter인 `string data`로 `"something://test"` 문자열을 확인하실 수 있습니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by JungUook** [comment]
감사합니다 해결되었습니다.
