### ISSUE TITLE
Hi, may I know how to add a close button on Android?

### ISSUE THREAD

**Issue by taehyeon-nhn** [nhn/gpm.unity#295]
Hi, may I know how to add a close button on Android?

안녕하세요, Android에서 닫기 버튼을 추가하는 방법을 알 수 있습니까?

_Originally posted by @cloudy3 in https://github.com/nhn/gpm.unity/issues/287#issuecomment-1280542035_

**Comment by taehyeon-nhn** [comment]
Hello. @cloudy3.

Please refer to the options below.
```cs
new GpmWebViewRequest.Configuration()
{
    ...
    isNavigationBarVisible = true,
    ...
}
```
The close button is dependent on navigation bar visible option.

Please refer to the [guide document](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#-api) and Sample.unity.
"Assets/GPM/WebView/Sample"

Thank you.

**Comment by cloudy3** [comment]
I see, thank you so much!

**Comment by taehyeon-nhn** [comment]
Thank you for your reply.
If you have any questions, please feel free to contact us.

Close this issue.
