### ISSUE TITLE
How can I open self signed url?

### ISSUE THREAD

**Issue by z3rgy** [nhn/gpm.unity#317]
I've been testing nhn unity webview and I was wondering how to open self signed url in the webview? 
It keeps on keeping me ssl_cilent_socket_impl.cc(982) handshake error.

**Comment by taehyeon-nhn** [comment]
Hello. @z3rgy.

SSL certificate errors could be ignored, but it makes the app vulnerable to man-in-the-middle attacks.
Please refer to the site below.
* https://support.google.com/faqs/answer/7071387?hl=en
* https://stackoverflow.com/questions/62890524/best-solution-for-the-handshake-failed-ssl-error-in-android-web-view-without-ign

If you have any questions, please feel free to contact us.
Thank you.

**Comment by taehyeon-nhn** [comment]
Close this issue.
