### ISSUE TITLE
Display PDF file or link from WebView

### ISSUE THREAD

**Issue by unobatbayar** [nhn/gpm.unity#321]
Hello! 

Thank you for great package and clean code. Is it possible to add `pdf` support for `WebView`?

## Service
* [X] WebView

**Comment by taehyeon-nhn** [comment]
Hello. @unobatbayar.
Thank you for using GPM.

In iOS, PDF is displayed.
Android will be downloaded if you have permissions.
I will let you know the contents after discussing it internally.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @unobatbayar.

We couldn't find a way to officially support it in Android WebView.
You can display the PDF in the following way.
```cs
GpmWebView.ShowUrl("https://docs.google.com/gview?embedded=true&url=pdf url", ...)
```
If you have any other ideas, please let us know.

If you have any questions, please feel free to contact us.
Thank you.

**Comment by unobatbayar** [comment]
@taehyeon-nhn 

I highly value your time. The method you provided works!

Thank you so much. 🎄☃️🌟🎁

**Comment by HardikaDoshi** [comment]
> Hello. @unobatbayar.
> 
> We couldn't find a way to officially support it in Android WebView. You can display the PDF in the following way.
> 
> ```cs
> GpmWebView.ShowUrl("https://docs.google.com/gview?embedded=true&url=pdf url", ...)
> ```
> 
> If you have any other ideas, please let us know.
> 
> If you have any questions, please feel free to contact us. Thank you.

I have tried out this method using a pdf url. The file gets downloaded directly into the file systems instead of rendering on the WebView. Can you please help out here.
