### ISSUE TITLE
Automate iOS setup of WebView

### ISSUE THREAD

**Issue by unobatbayar** [nhn/gpm.unity#329]
Hello, 

Sorry to bother again, we want to really use this package, however we use CI/CD server and we can't manually setup Xcode after building.

It possible to automate iOS setup process?

![Screenshot 2022-12-27 at 14 19 12](https://user-images.githubusercontent.com/38866249/209615098-1c1e6275-642e-412f-bb07-8e932f569817.png)

we really need to automate adding of GPMWebView.bundle to Copy Resources Bundle but had no luck in BuildProcessor scripts because on iOS the WebView buttons don't appear/

**Comment by taehyeon-nhn** [comment]
Hello. @unobatbayar.

Depending on the Unity version, it may be added or skipped, so it is difficult to apply in common.
Please refer to the Unity [OnPostprocessBuild](https://docs.unity3d.com/ScriptReference/Build.IPostprocessBuildWithReport.OnPostprocessBuild.html) and [PBXProject](https://docs.unity3d.com/ScriptReference/iOS.Xcode.PBXProject.html) class to add a `GPMWebView.bundle` to a specific Unity version.

If you have any questions, please feel free to contact us.
Thank you.

**Comment by unobatbayar** [comment]
I understand, thank you

**Comment by unobatbayar** [comment]
If anyone want to automate:

In `OnPostprocessBuild` add
```cs
                var webViewBundleGuid = pbxProject.AddFile("Frameworks/GPM/WebView/Plugins/IOS/GPMWebView.bundle", "GPMWebView.bundle", PBXSourceTree.Build);  
                pbxProject.AddFileToBuild(appGuid, webViewBundleGuid);
```
It will be added automatically when you build for iOS 👍 
![Screenshot 2022-12-28 at 10 33 20](https://user-images.githubusercontent.com/38866249/209743453-bc328688-03da-4b88-a04d-55ff0532ed3b.png)
