### ISSUE TITLE
마진 값을 통한 유니티 UI 호출

### ISSUE THREAD

**Issue by RowdyCOSON** [nhn/gpm.unity#351]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
안녕하세요 여쭤 볼게 있습니다.
Gree의 웹뷰와 같이 마진 설정을 통한 마진 값 밖의 유니티 UI의 클릭과 같은 호출은 GPM웹뷰에서 불가능한가요?

혹여 불가능하다면
위 기능의 개발이 있으면 좋을거 같습니다.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by taehyeon-nhn** [comment]
@RowdyCOSON님. 안녕하세요.

유니티 UI 클릭 등을 위해 WebView의 Texture 지원을 개발 계획에 포함하고 있습니다.
아직 정확한 개발 일정이 정해지지 않은 점 양해 부탁드리며,
개발 완료 및 배포되면 댓글을 통해 전달드리겠습니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @RowdyCOSON님.

WebView v2.0.0이 배포되었습니다.
팝업 영역만 이벤트 처리에 사용되게 수정되었습니다.
GPM WebView의 SampleWebView.cs 파일과 [ReleaseNotes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#200)를 참고 부탁드립니다.

감사합니다.
