### ISSUE TITLE
WebView 문의

### ISSUE THREAD

**Issue by gameproj** [nhn/gpm.unity#352]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
- 최신 버전

## Summary

앱 업데이트 이후, 사진상의 왼쪽 코드 (깃헙 문서의 예제와 비슷) 사용시, Null 에러 발생

## Screenshots

![image](https://user-images.githubusercontent.com/6613017/215403399-df0d6b57-ddfc-4a30-afe8-284d652de1fe.png)

## Additional context

기존에 되던 코드 (왼쪽) 소스가, GPM 업데이트 이후 Null 오류 발생하여, 
찾아보니 customSchemePostCommand 가 생겼던데 이 값이 필수 값 인게 맞는지 확인 요청드립니다.

WebView 메인 문서의 경우 customSchemePostCommand 관련 내용이 설명에는 있지만, '예제'에는 없어서요.

**Comment by smflt-nhn** [comment]
@gameproj
안녕하세요

customSchemePostCommand 에서 null 오류가 1.11.1에서 해결되어 배포되었습니다.
1.11.1 버전으로 확인 부탁드립니다.

감사합니다.

https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md#1111

**Comment by gameproj** [comment]
확인했습니다, SDK 업데이트를 한번 더 진행해야 할 것 같네요..! 감사합니다.
