### ISSUE TITLE
Webview Not Working

### ISSUE THREAD

**Issue by ZeeshanAliTll** [nhn/gpm.unity#353]
Hello i just imported the WebView in my project and play the sample Scene but nothing happens it is not opening the WebView?

**Comment by taehyeon-nhn** [comment]
Hello. @ZeeshanAliTll.

Android or iOS build is required to run the WebView.
If you don't see the Sample.unity, please check the contents below:
* Unity version
* Target platform
* Additional information

If you have any questions, please feel free to contact us.
Thank you.

**Comment by ZeeshanAliTll** [comment]
I am using unity version 2020.3.8  
Target platform is android and when i build the sample.unity nothing happens when i click on Webview button

**Comment by taehyeon-nhn** [comment]
Thank you for your reply. Let me check this issue.

**Comment by taehyeon-nhn** [comment]
Hello. @ZeeshanAliTll.

Unity 2020.3.8f1 build has verified normal excution in the mobile device.
Please check the device environment information and more details about the issue that is not being used.

Please refer the [Guide document](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#android).

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @ZeeshanAliTll.

We're closing this issue, please reopen it if you have any further questions.

If you have any additional questions, please feel free to contact us.
Thank you.
