### ISSUE TITLE
Remove White Background

### ISSUE THREAD

**Issue by SeyU98** [nhn/gpm.unity#354]
## Service

* WebView

## Version
GPM 2.2.2 - WebView 1.11.1

## Summary
Hi.. I have a question. Can I remove the first white background when open the WebView in first time?
or there a step to make Load Complete first before WebView show?

**Comment by SeyU98** [comment]
https://user-images.githubusercontent.com/31847564/219588115-667574e3-b6e9-4d65-bc11-b6d2729e04ce.mp4

The White Background when open webview before page loaded

**Comment by taehyeon-nhn** [comment]
Hello. @SeyU98.

Current version does not support those features.
We will discuss the development within the team and let you know by comment.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @SeyU98.

We decided to development webview background changes and callback additions.
The schedule is undecided, and we will let you know through comments or release notes when the development is completed.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @SeyU98.

WebView background color specification and web page started callback have been added.
Please refere the [ReleaseNotes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.en.md#1120).

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @SeyU98.

We're closing this issue.

If you have any additional questions, please feel free to contact us.
Thank you.

**Comment by SeyU98** [comment]
Thankyou for adding the features, sorry for late response
