### ISSUE TITLE
InfiniteScroll에서 UpdateData 함수가 불필요하게 많이 호출되는 현상.

### ISSUE THREAD

**Issue by kzinnia** [nhn/gpm.unity#355]
## Service

* [ ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [O ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version

UI 2.7.0

## Describe the bug

InfiniteScroll에서 UpdateData(InfiniteScrollData scrollData) 함수가 불필요하게 많이 호출되는 현상.

## To Reproduce

1. 제공된 SampleScene.unity 를 Open.
2. Insert Data 버튼을 통해 Data를 두 개 추가.
3. 마우스를 이용하여 아래로 드래그 스크롤
4. 매 프레임마다 UpdateData가 호출됨.

첫번째 Data가 화면에 보여지는 상태일 때, 스크롤이 발생하는 동안에, 매 프레임 마다 UpdateData가 호출됨.
첫번째 Data가 화면에서 사라지면, 정상적으로 UpdateData가 호출됨.
유니티 에디터 상에서 확인 가능.

## Expected behavior

Data가 화면에 등장하거나 사라질때에만 UpdateData가 호출되어야함.

### Unity
- Version 2022.2.6

### Desktop (please complete the following information):
 - OS: Adroid,

**Comment by smflt-nhn** [comment]
@kzinnia 
안녕하세요.

버그 제보 감사합니다.
버그를 확인하고 수정하였으며 수정된 패키지를 전달드립니다.

[gpm_ui_v2.7.1.zip](https://github.com/nhn/gpm.unity/files/10763016/gpm_ui_v2.7.1.zip)

감사합니다.

**Comment by kzinnia** [comment]
수정된 것 확인했습니다. 빠른 대응 감사합니다!
