### ISSUE TITLE
InfiniteScroll에서 Item 추가 직후에 MoveTo호출 관련 문의

### ISSUE THREAD

**Issue by kzinnia** [nhn/gpm.unity#356]
## Service

* [ ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [O ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
2.7.0

## Summary
InfiniteScroll에서 샘플을 열어,
InfiniteScrollSample.cs 에 아래와 같이 테스트 코드를 추가해보았습니다.

        public void Button_InsertData()
        {
            for (int i = 0; i < 100; i++)
            {
                InsertData();
            }

            verticalScrollList.MoveTo(99, InfiniteScroll.MoveToType.MOVE_TO_CENTER);
        }

99번째 아이템으로 이동하도록 버튼을 하나 만들어서 테스트 해보았지만, 작동하지 않는 것 같습니다.

        public void Button_InsertData()
        {
            for (int i = 0; i < 100; i++)
            {
                InsertData();
            }
            verticalScrollList.UpdateAllData();  // 여기에 추가
            verticalScrollList.MoveTo(99, InfiniteScroll.MoveToType.MOVE_TO_CENTER);
        }

InsertData후에, UpdateAllData()를 실행하니 정상 작동하는데,
해당 방법으로 초기화 하는 것이 맞는 방법인지 질문 드립니다.

**Comment by smflt-nhn** [comment]
@kzinnia 
안녕하세요.

InsertData를 호출하면 즉시 업데이트 하지않고 지연 업데이트 합니다.
즉시 업데이트 하고 싶을 경우 InsertData(data, true)로 immediately 인수를 true로 넣으면 즉각 업데이트를 합니다.
InsertData를 여러개 호출 한뒤 UpdateAllData로 갱신하는 방식은 정상적인 방법이 맞으나
time이 들어가지 않는 MoveTo일 경우 바로 갱신되는것이 타당한것 같습니다.

수정한 패키지 파일 입니다.
[gpm_ui_v2.7.1.zip](https://github.com/nhn/gpm.unity/files/10779912/gpm_ui_v2.7.1.zip)

감사합니다.

**Comment by kzinnia** [comment]
보내주신 파일로 작동확인했습니다. 감사합니다!
