### ISSUE TITLE
Webview w/ ReactJS and HTML5 that requires JS, crashing?

### ISSUE THREAD

**Issue by abphaiboon** [nhn/gpm.unity#376]
## Service

* [X] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Main

## Summary
Currently im creating a mobile game "lobby" where it should launch iframe/html based games. When I try to launch the game, it crashes, or returns JS callback null? This happens on ReactJS based projects and HTML5 Games. i try to embed using the webview.

## Screenshots
Loading ReactJS Based Page:
![image](https://user-images.githubusercontent.com/12667893/230678865-542be6fe-8762-4387-bf0d-35880bc22c1e.png)

Loading HTML5 Game in Webview:
![image](https://user-images.githubusercontent.com/12667893/230678995-0353b8ae-f0ad-4d0c-bac5-d683b8e20bb5.png)

## Additional context
Im going to try to open the APK in android studio, and see if i can get full debug logs. Ill comment with result.

**Comment by taehyeon-nhn** [comment]
Hello. @abphaiboon.
Thank you for using GPM.

Could you provide us with any code or pages we can test to investigate the issue more thoroughly?

Thank you.

**Comment by abphaiboon** [comment]
Any way I can DM you or discord? Link is to a private react project.

**Comment by taehyeon-nhn** [comment]
Using DM or Discord is currently difficult for internal use.
It would be helpful if you could provide us with a sample that contains some executable code, even if it's just a small part.
