### ISSUE TITLE
Disable web view naviguation system ?

### ISSUE THREAD

**Issue by antoinenisoli** [nhn/gpm.unity#378]
Hi,
Is it possible to disable the naviguation system of a web view on mobile ? For example, if i want to display a youtube video but i don't want my user to scroll down and watch other videos ? I know it is possible to hide the naviguation bar but i didn't find any way to block the scrolling system.

**Comment by taehyeon-nhn** [comment]
Hello. @antoinenisoli.

We are not currently setting specifications for the scroll bar. After sharing this information with our team, we will provide guidance on the development direction.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @antoinenisoli.

Is it possible to use the embed tag on the web page?
It would be nice to have more detailed usage information.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @antoinenisoli.

If you are unable to provide further information, we will close the issue.

If you have any additional questions, please feel free to contact us.
Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @antoinenisoli.

We're closing this issue.

If you have any additional questions, please feel free to contact us.
Thank you.
