### ISSUE TITLE
Unity 2021.3.24f1 

### ISSUE THREAD

**Issue by Pacman18** [nhn/gpm.unity#388]
## Service

* [ ] Unity Version 에 따른 지원 2021.3.24f1 

## Version
2.2.3

## Describe the bug
유니지 지원 안하는 버전확인이 필요할듯 합니다. 
2021.3.24f1  에서 

gpm : 2.2.3
최신버전을 다운받으면 존재하지 클래스를 사용한 내용이 확인됩니다. 

## Screenshots

![버그리포트](https://user-images.githubusercontent.com/7939150/236380573-f73601e3-29ef-423d-9be0-351b6b4ffd17.PNG)

### Unity
Unity 2021.3.24f1

### Desktop (please complete the following information):
 - OS: Window 10 
 - Browser [chrome]

**Comment by smflt-nhn** [comment]
@Pacman18 

해당 내용 수정된 Common 2.3.1 업데이트 되었습니다.
Common 2.3.1 포함된 Manager 2.2.4 배포 준비 중 입니다. 

감사합니다.

**Comment by smflt-nhn** [comment]
@Pacman18 
수정 적용된 Manager 2.2.4 가 배포되었습니다.

감사합니다.
