### ISSUE TITLE
유니티 2022.2.17 로 마이그레이션 후 컴파일 오류

### ISSUE THREAD

**Issue by ParkEunSeong** [nhn/gpm.unity#395]
## Service

* [ ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

## Additional context

유니티 2020버전을 쓰다 2022로 마이그레이션을 진행하였는데 컴파일 오류가 발생합니다.
![image](https://github.com/nhn/gpm.unity/assets/11013810/d77820e3-d259-431b-9c7c-f2c6ba84375e)

유니티내 설정 문제가 필요한지 확인 부탁해주시면 감사하겠습니다.

**Comment by ParkEunSeong** [comment]
API Level 변경 후 에러가 사라졌네요.

**Comment by smflt-nhn** [comment]
@ParkEunSeong

안녕하세요. 
Common 2.3.1로 업데이트 또는 Manager 2.2.4 업데이트하시면 API Level 상관없이 해결됩니다.

감사합니다.
