### ISSUE TITLE
About close safe browsing from script

### ISSUE THREAD

**Issue by w05191998** [nhn/gpm.unity#396]
Hi Team, firstly I need to express my thanks in this project, I believe it helps a lot of people.
Is it possible to close the safe browsing window through script? I tried Close() method but it didn't works. Thank you again.

**Comment by taehyeon-nhn** [comment]
Hello. @w05191998.

For GpmWebView SafeBrowsing, we do not provide a Close API.
If the Close API is added in the future, we will let you know in the comments.

Thank you.

**Comment by w05191998** [comment]
Thank you
