### ISSUE TITLE
Inspector settings bug in tab controller

### ISSUE THREAD

**Issue by choidaewon** [nhn/gpm.unity#402]
## Service

* [ ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [x] UI 
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
GPM 2.2.4
UI 2.7.2

## Describe the bug
Tab controller's Link item is not saved in Prefab Inspector.

## To Reproduce
1. Create a UI with TabController.
2. Convert the UI to Prefab and enter Prefab mode.
3. Configure and save the TabButton and TabPage within the UI.
(*see sample provided by GPM)
4. Configure the Link part of the TabController inspector items.
Save button in prefab mode is still disabled.
5. If you exit Prefab mode and check the TabController in the hierarchy, you can see that the changes in the Link part are lost.

## Expected behavior
If this function works, your changes should persist.

## Screenshots
![image](https://github.com/nhn/gpm.unity/assets/93138242/721f4593-843c-48a2-875f-b7bcf2a08c8e)
![image](https://github.com/nhn/gpm.unity/assets/93138242/7fd6a70f-9f05-48e0-a04e-2705729e47bf)

* Even though the prefab is not overridden, the contents are different in hierarchy and prefab mode

### Unity
- Version 2022.2.13

### Desktop (please complete the following information):
 - OS: [windows 11]

## Additional context
I would appreciate it if you could suggest a quick fix or temporary solution to the problem.

**Comment by smflt-nhn** [comment]
Hello @choidaewon 

Thanks for reporting the bug. 

Please apply and check the modified package.

[gpm_ui_v2.7.2_fix.zip](https://github.com/nhn/gpm.unity/files/11570268/gpm_ui_v2.7.2_fix.zip)

thank you.

**Comment by choidaewon** [comment]
> 안녕하세요@choidaewon
> 
> 버그를 보고해 주셔서 감사합니다.
> 
> 수정된 패키지를 확인 후 신청해주세요.
> 
> [gpm_ui_v2.7.2_fix.zip](https://github.com/nhn/gpm.unity/files/11570268/gpm_ui_v2.7.2_fix.zip)
> 
> 감사합니다.



> Hello @choidaewon
> 
> Thanks for reporting the bug.
> 
> Please apply and check the modified package.
> 
> [gpm_ui_v2.7.2_fix.zip](https://github.com/nhn/gpm.unity/files/11570268/gpm_ui_v2.7.2_fix.zip)
> 
> thank you.

The problem is solved and it works fine.

Thank you for your quick action.
