### ISSUE TITLE
Deprecation in CacheStorage - Fix Provided

### ISSUE THREAD

**Issue by alxspiker** [nhn/gpm.unity#414]
## Service
* [X] Cache Storage

## Version
Version 2.2.4

## Describe the bug
`request.isNetworkError` and `request.isHttpError` in `GPM/CacheStorage/Sample/CacheStorageSample.cs` produce a deprecation warning.

## Fix:
In CacheStorageSample.cs on line 187, replace
`request.isNetworkError || request.isHttpError`
with
`(request.result == UnityWebRequest.Result.ConnectionError) || (request.result == UnityWebRequest.Result.ProtocolError)`

## To Reproduce
1. Install UI package.

### Unity
2022.3.4f1

**Comment by smflt-nhn** [comment]
Thanks for reporting the bug.

We'll fix it soon.
