### ISSUE TITLE
AOS 환경에서 웹뷰가 세이프에어리어에서는 랜더링이 안되는데 랜더링이 되게 하려면 어떻게 해야 하나요

### ISSUE THREAD

**Issue by Deokeun-Kim** [nhn/gpm.unity#417]
## Service

* [O ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by Deokeun-Kim** [comment]
IOS는 세이프에어리어에도 Web View 영역이 풀스크린으로 표시되고있고,
안드로이드 일때만 웹뷰에서 풀스크린으로 웹뷰를 설정하였는데도,
윗 노치 영역만큼 웹뷰가 표시되지 않습니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Deokeun-Kim님.
GPM을 사용해 주셔서 감사합니다.

조금 더 정확한 확인을 위해 아래 정보 추가를 부탁드립니다.
* Unity Editor 버전
* Android min/target SDK 버전
* GpmWebView의 ShowUrl을 호출할 때의 정보
* 이슈 해결을 위해 도움이 되는 스크린샷(이 부분은 가능하시면 첨부 부탁드립니다.)

감사합니다.

**Comment by Deokeun-Kim** [comment]
Unity Editor : 2021.3.23f1
Android min/target SDK : 24 / 31
GpmWebView의 ShowUrl을 호출할 때의 정보 : 
```c#
_webViewOption = new GpmWebViewRequest.Configuration()
{
	style = GpmWebViewStyle.FULLSCREEN,
	orientation = GpmOrientation.PORTRAIT,
	isClearCookie = false,
	isClearCache = false,
	isNavigationBarVisible = true,
	navigationBarColor = "#000000",
	title = "",
	isBackButtonVisible = true,
	isForwardButtonVisible = true,
	supportMultipleWindows = true,
	isMaskViewVisible = true,
	contentMode = GpmWebViewContentMode.MOBILE
};
``` 
해당 현상에 대한 스크린샷 공유드립니다.
![GPM 웹뷰 뒷 UI 보이는 현상](https://github.com/nhn/gpm.unity/assets/79882975/d4ec1ada-7afb-4518-b8be-3264ecfaf7c5)

**Comment by Deokeun-Kim** [comment]
안녕하세요 태현님

요청하신 정보 추가하여서 해당 질문에 추가적으로 댓글 남겼습니다.
확인 부탁드립니다.

감사합니다.

2023년 7월 12일 (수) 오후 7:39, 김태현 ***@***.***>님이 작성:

**Comment by taehyeon-nhn** [comment]
@Deokeun-Kim님 안녕하세요.
추가 정보 공유 감사합니다.
내용 확인 후 전달드리겠습니다.

**Comment by harrywkd5300** [comment]
혹시 이 이슈 해결된 이슈일까요??

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Deokeun-Kim님.

GPM WebView v2.0.0이 업데이트되며 Android 및 iOS 내부 로직이 크게 변경되었습니다.
문의하신 내용의 경우 현상 재현과 추가 수정 여부의 확인이 필요한 상황이나 
현재 다른 이슈 대응으로 확인이 늦어지는 점 양해 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Deokeun-Kim님.

GPM WebView v2.0.1에서 WebView 크기 및 위치 계산 로직이 수정되었습니다.
시간 되실 때 문의하신 현상이 확인 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Deokeun-Kim 님.

이슈 종료하겠습니다.
추가 문의 사항이 있으면 언제든 편하게 문의 부탁드리며, 신규 문의의 경우 새로운 이슈로 등록 부탁드립니다.

감사합니다.
