### ISSUE TITLE
when I using  WebView there is no keyboard show for write in Oculus quest 2 please do helpful ASAP

### ISSUE THREAD

**Issue by raj-kanjariya** [nhn/gpm.unity#420]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by taehyeon-nhn** [comment]
Hello. @raj-kanjariya.

We need more details.
* Unity Editor versions
* Platform information and SDK version
* Information about how you used GPM WebView and your configuration settings

It would be nice to see additional screenshots.

Thank you.

**Comment by spin-nhn** [comment]
@raj-kanjariya 
Since there has been no response for a long time, we will close the issue.
