### ISSUE TITLE
Popup webview

### ISSUE THREAD

**Issue by OmedMilat** [nhn/gpm.unity#421]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
2.2.5

## Summary
When using the webview in popup mode, the elements underneath the webview becomes non interactable. I want to be able to click some button or drag something in Unity while the webview is open. Is something like this possible or not? 

## Additional context
For implementation i have followed this tutorial: https://www.youtube.com/watch?v=CmsRC3X0pNA (i am new to Unity)

**Comment by taehyeon-nhn** [comment]
Hello. @OmedMilat.
First of all, thank you for using GPM.

Unfortunately, we do not support that feature at this time.
We are working on developing GPM WebView to be able to display WebViews through Unity Game Objects.
Please check out our guide documentation for future updates.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @OmedMilat.

WebView 2.0.0 has been deployed.
Set the WebView to occupy only the size of the popup area.
Please refer to the SampleWebView.cs file and [ReleaseNotes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.en.md#200)

Thank you.
