### ISSUE TITLE
How to disable closing of webview with "Back" button, but still let to go back to prev pages?

### ISSUE THREAD

**Issue by al1472av** [nhn/gpm.unity#422]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
2.2.5

## Summary
I am using default fullscreen webview. When i click "Back", it goes back, when there is no more pages to go back, webview just closes itself. How i can disable ability to close webview. I just want user to go back to previous pages, not to close whole webview.

**Comment by taehyeon-nhn** [comment]
Hello. @al1472av.
First of all, thank you for using GPM.

We've decided to add a callback that doesn't handle the exit when the webview exits during the action of the back button.
We'll let you know in the comments when the fix is complete.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @al1472av.

WebView 2.0.0 has been deployed.
Please refer to the SampleWebView.cs file.
```
new GpmWebViewRequest.Configuration()
{
    ...
    isBackButtonCloseCallbackUsed = true
}

private void OnWebViewCallback(GpmWebViewCallback.CallbackType callbackType, string data, GpmWebViewError error)
{
    switch (callbackType)
    {
        case GpmWebViewCallback.CallbackType.BackButtonClose:
            break;
    }
}
```

Thank you.
