### ISSUE TITLE
Can I remove close button

### ISSUE THREAD

**Issue by khushal1220** [nhn/gpm.unity#423]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
1.12.1 Version Web View

## Summary

Hey There, I am using web view for a fairly long time now. but I have to remove the close button from view as it is required on a project I am working on currently if there are any possible ways then plz tell me if possible I really need this. and i didn't have any idea 

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by taehyeon-nhn** [comment]
Hello. @khushal1220.

Currently, there is no visible setting for the close button in the WebView settings.
We'll add one, and let you know in the comments when we're done.

Thank you.

**Comment by khushal1220** [comment]
> Contributor

hey, there is it possible to open the browser from where we left off last time just asking if any web view sdk has this capability. Because i need this functionality and no where to found

**Comment by taehyeon-nhn** [comment]
Hello. @khushal1220.

`there is it possible to open the browser from where we left off last time just asking if any web view sdk has this capability.`
Could you explain this in a little more detail?

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @khushal1220.

WebView 2.0.0 has been deployed.
Please refer to the SampleWebView.cs file.
```
new GpmWebViewRequest.Configuration()
{
    ...
    isCloseButtonVisible = false
}
```
Thank you.
