### ISSUE TITLE
Can I load prev page from where is left before killing app?

### ISSUE THREAD

**Issue by khushal1220** [nhn/gpm.unity#426]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
I want to know if can i load the same previous page which I used before killing/closing the app? from cache storage or any other method. It will help me a lot. Btw you are still helping a lot by providing free services.

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by taehyeon-nhn** [comment]
Hello. @khushal1220.

The WebView does not save the previous page.
We'll check into adding the feature to save previous pages and let you know in the comments.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @khushal1220.

When using [cache storage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) in WebView, there are likely to be problems with saving resources and refreshing pages.
It seems like we could use [Unity PlayerPrefs](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html) to store previous URLs, is there a reason why this is difficult to use?

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @khushal1220.

Close the issue because there are no further responses.
If you have any questions, please feel free to contact us.

Thank you.
