### ISSUE TITLE
iOS 에서 웹뷰가 흰화면만 뜨는 증상 (프레임 로드 중단됨 에러)

### ISSUE THREAD

**Issue by Nautilus0409** [nhn/gpm.unity#427]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version

GPM 2.2.5

WebView 1.12.1

## Summary
`        
GpmWebView.ShowUrl(
            url,
            new GpmWebViewRequest.Configuration()
            {
                style = GpmWebViewStyle.POPUP,
                orientation = GpmOrientation.PORTRAIT,
                isClearCookie = true,
                isClearCache = true,
                isNavigationBarVisible = true,
                supportMultipleWindows = true,
#if UNITY_IOS
            contentMode = GpmWebViewContentMode.MOBILE,
            isMaskViewVisible = true,
#endif
            }, 
            null,
            null);
`

안드로이드 에서는 웹뷰가 잘 뜨는데 iOS 에서는 웹뷰창은 켜지는데 안에 내용이 흰 화면만 뜨고 뜨질않습니다.

로그를 추적해보니 해당 메시지를 얻을 수 있었습니다.

⚠️[GPM][WebView][iOS][GPMWebViewController.m:(1113)] Error occurred while loading content. Error Domain=WebKitErrorDomain Code=102 "프레임 로드 중단됨" UserInfo={_WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x2815efa80>, NSErrorFailingURLStringKey=, NSErrorFailingURLKey=, NSLocalizedDescription=프레임 로드 중단됨}

Xcode 설정도 가이드대로 완료했습니다.

질문 내용
1.  제가 놓친 부분이 있을까요?
2.  URL에 한글이 포함되면 어떻게 처리해야하나요?
3.  Code=102 "프레임 로드 중단됨" 에러는 어떤 상황에서 발생하나요?

## Screenshots
If applicable, add screenshots to help explain your question.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Nautilus0409 님.
GPM을 사용해 주셔서 감사합니다.

문의에 대한 답변 전달드립니다.
1. 설정한 내용에 잘못된 부분은 없는 듯 합니다.
2. URL에 한글이 포함되는 경우 한글 그대로 입력하시면 됩니다. WebView 내부에서 인코딩 작업이 진행됩니다.
3. Code=102 프레임 로드 중단 오류를 확인하지는 못했습니다. 확인 가능한 URL을 전달해 주시면 추가 확인해보겠습니다.

감사합니다.

**Comment by Nautilus0409** [comment]
답변 주셔서 감사합니다.

원인은 한글이 포함된 URL을 UTF-8 로 인코딩해서 파라미터에 넣어서 그런것 같습니다.

해당 Url을 디코딩해서 그대로 파라미터에 넣으니 AOS, IOS 둘다 작동합니다.

**Comment by taehyeon-nhn** [comment]
@Nautilus0409 님 확인 감사합니다.
추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
이슈 클로즈하겠습니다.
