### ISSUE TITLE
Google Web Login 403 Error

### ISSUE THREAD

**Issue by Nautilus0409** [nhn/gpm.unity#428]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
1.12.1

## Summary
웹뷰로 구글 로그인을 구현해보려고 하고있습니다.

자료 조사 결과 보안상의 이슈로 웹뷰를 통한 인증은 구글에서 차단하고있다고하는데요.

useragent 값을 수정하면 우회할 수 있다는 내용을 봐서 수정하고 시도했더니 일단 구글 아이디를 입력하는 창은 떴습니다.
(참고 : https://github.com/nhn/gpm.unity/issues/200)

하지만 아이디를 입력하고나니 다시 403 에러가 납니다. 

방법이 없을까요? 

## Screenshots
![image](https://github.com/nhn/gpm.unity/assets/76603104/511b8fe6-b325-458d-b3f0-1d83785ea071)

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Nautilus0409님.
GPM을 사용해 주셔서 감사합니다.

먼저 구글의 [WebView를 통한 OAuth 해결](https://support.google.com/faqs/answer/12284343?hl=ko) 글을 참고 부탁드립니다.

GPM WebView에서 Chrome 맞춤 탭은 [ShowSafeBrowsing](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#showsafebrowsing)으로 제공하고 있습니다.
[플랫폼별 설정](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#-%ED%94%8C%EB%9E%AB%ED%8F%BC%EB%B3%84-%EC%84%A4%EC%A0%95)과 함께 참고 부탁드립니다.

감사합니다.

**Comment by Nautilus0409** [comment]
@taehyeon-nhn  답변 해주셔서 감사합니다.

기본 브라우저가 크롬이 아닌 앱플레이어( 녹스, LD 플레이어)  는 기본 브라우저를 크롬으로 설정 하기 전까지 
ShowSafeBrowsing 으로 해도 403이 발생하는데, 제가 놓친 부분이 있는걸까요? 아니면 크롬으로 설정을 해야만 동작하는건가요?

**Comment by taehyeon-nhn** [comment]
@Nautilus0409님.

문의 주신 부분은 확인 후 내용 전달드리겠습니다.

감사합니다.

**Comment by Z5SteveKim** [comment]
@Nautilus0409 님 안녕하세요.
도움이 될지모르겠지만 제가 해결한 방법을 말씀드리겠습니다.

웹뷰 Configuration 에 userAgentString = "Mozilla/5.0 AppleWebKit/535.19 Chrome/56.0.0 Mobile Safari/535.19", 와 같은 셋팅을 커스텀하게 주시면될거 같습니다.

저는 ShowSafeBrowsing 해당 옵션을 설정해도 안되다가 위의 옵션을 설정하니 해결 되었습니다.
안전성은...^^;;;

**Comment by Nautilus0409** [comment]
@Z5SteveKim  답변 감사합니다.
말씀해주신 부분은 이미 처리하고 그다음페이지에서 같은에러가 나서 문의 드렸습니다

**Comment by Z5SteveKim** [comment]
@Nautilus0409 아 그렇군요..
저는 같은 셋팅으로 다음 페이지까지 사이트 이용에 문제 없었어서요.
다른 이슈일듯하네요.
죄송합니다.

**Comment by spin-nhn** [comment]
> @taehyeon-nhn 답변 해주셔서 감사합니다.
> 
> 기본 브라우저가 크롬이 아닌 앱플레이어( 녹스, LD 플레이어) 는 기본 브라우저를 크롬으로 설정 하기 전까지 ShowSafeBrowsing 으로 해도 403이 발생하는데, 제가 놓친 부분이 있는걸까요? 아니면 크롬으로 설정을 해야만 동작하는건가요?

@Nautilus0409 님 안녕하세요.
ShowSafeBrowsing API 호출 시, 크롬이 아닌 기본 브라우저로 표시되는 현상이 확인되어 수정되었으며, 다음 배포에 포함할 예정입니다. 추가 답변이 늦어 죄송합니다.

**Comment by spin-nhn** [comment]
@Nautilus0409 
GPMWebView 2.1.0 버전에서 수정되었습니다.
감사합니다.

* [GPM WebView 2.1.0 Release notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md)
