### ISSUE TITLE
IOS 웹뷰 닫기 버튼 보이지 않는 현상 문의

### ISSUE THREAD

**Issue by ParkEunSeong** [nhn/gpm.unity#433]
## Service

* [ ] WebView

## Version
Write the version that you are currently using.

## Describe the bug
Close 버튼 활성화를 했는데 ios 단말에서는 닫기 버튼이 보이지는 않고 
닫기 버튼이 있어야할 위치를 탭하면 웹뷰는 닫힙니다.
안드로이드에서는 정상적으로 [동작합니다.]
![image](https://github.com/nhn/gpm.unity/assets/11013810/4c09b913-414d-4643-a06b-8249a7bb66b0)
### Unity
- Version

### Smartphone (please complete the following information):
 - Device: IPad, IPhone

**Comment by taehyeon-nhn** [comment]
안녕하세요. @ParkEunSeong 님.

iOS 빌드에서 가이드의 [GPMWebView.bundle](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#gpmwebviewbundle)이 추가되어 있는지 확인 부탁드립니다.

GPMWebView.bundle이 추가된 상태에서도 동일한 현상이 나타난다면 아래 내용 확인 부탁드립니다.
* Unity Editor version
* iOS SDK version, iOS Device version
* GpmWebView.ShowUrl에 전달한 Configuration 내용 및 공유 가능한 code
* Unity Editor 또는 Xcode에 추가 설정한 공유 가능한 정보

감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @ParkEunSeong 님.

전달드린 내용으로 문제가 해결되었는지 궁금합니다.
추가 문의 사항이 있으면 언제든 편하게 문의 부탁드리며, 신규 문의의 경우 새로운 이슈로 등록 부탁드립니다.

감사합니다.

**Comment by taehyeon-nhn** [comment]
이슈 종료하겠습니다.
추가 문의 사항이 있으면 언제든 편하게 문의 부탁드리며, 신규 문의의 경우 새로운 이슈로 등록 부탁드립니다.
