### ISSUE TITLE
IOS 환경에서 느린 통신에 의해서 상단의 닫기 버튼이 늦게 나타나는 현상

### ISSUE THREAD

**Issue by Cmho88** [nhn/gpm.unity#434]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
IOS 환경에서 매우 느린 네트워크 속도 일 때, 웹 사이트의 로딩이 완료 된 후 매우 늦게 닫기 버튼이 나타납니다.
닫기 버튼을 웹 사이트보다 먼저 노출 시켜서 로딩에 오랜 시간이 걸릴 경우 언제든 웹 뷰를 닫을 수 있도록 하고싶습니다.
어떻게 해야 할까요?

## Screenshots
![image](https://github.com/nhn/gpm.unity/assets/91856879/d31c0b87-db07-4063-b4e3-32c95e3c0d3e)

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Cmho88 님.

현재의 GPM WebView 버전에서는
[ShowUrl API](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#showurl) 사용 이후 Timeout을 통해 [Close API](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#close)를 호출하는 방식을 생각해 볼 수 있을 것 같습니다.

GPM WebView에서 UI 우선 활성화에 대한 기능은
실제 적용에 이슈가 없는지 등을 확인 후 내용 공유드리겠습니다.

감사합니다.

**Comment by Cmho88** [comment]
로딩 시간이 오래 걸리지만 결국 닫기 버튼과 웹 사이트의 로딩이 완료되기 때문에
Timeout 을 통한 강제 종료 처리는 적절하지 않을 것 같습니다.

감사합니다.

**Comment by spin-nhn** [comment]
@Cmho88 안녕하세요.
다음 배포에 해당 사항 적용될 예정입니다. 의견 주셔서 감사합니다.

* (iOS) 페이지 로딩 완료 전, 닫기 버튼 노출

**Comment by spin-nhn** [comment]
@Cmho88 
GPMWebView 2.1.0 버전에서 수정되었습니다.
감사합니다.

* [GPM WebView 2.1.0 Release notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md)
