### ISSUE TITLE
iOS에서 비디오태그가 들어간 동영상이 자동 재생이 되지 않습니다.

### ISSUE THREAD

**Issue by Kwansik-Jung** [nhn/gpm.unity#435]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

## Additional context

안녕하세요.
제목 그대로 입니다.
iOS에서 비디오태그가 들어간 동영상이 자동 재생이 되지 않습니다.
웹뷰에서 다음의 옵션을 켜야될 것 같은데 GPM에서 해당 옵션을 컨트롤 할 수 있는 방법이 보이지 않아서 문의드립니다.

webConfiguration.allowsInlineMediaPlayback = true
webConfiguration.mediaTypesRequiringUserActionForPlayback = []
webConfiguration.mediaTypesRequiringUserActionForPlayback = .audio

제가 원하는 것은 제목처럼 ios에서 gpm 웹뷰로 들어간 웹사이트에 만약 비디오태그가 있다면 자동재생을 시키는 것입니다.
기능 추가가 가능할까요?
감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @kwansikjung 님.

전달해 주신 기능에 대해 확인해보겠습니다.
추가로 개발 환경에 대한 내용 공유 부탁드립니다.
* Unity Editor version
* Target SDK
* Target minimum iOS Version

감사합니다.

**Comment by kwansikjung** [comment]
유니티 버전은 2021.3.29f1
미니멈 iOS 타깃 SDK 버전은 12
Target SDK는  Device SDK 입니다. (iPhone + iPad)

**Comment by kwansikjung** [comment]
안녕하세요.
결과가 어떻게 되었는지 궁금합니다.
이후 답글이 없어서 계속보고계신건지 아니면 계획에없으신건지 알려주실 수 있으신지요.
감사합니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @kwansikjung님.

답변이 늦어 죄송합니다.
문의하신 내용의 경우 다른 기능 개발 및 수정의 이유로 대응이 늦어지고 있는 점 양해 부탁드립니다.
추가로 GPM WebView의 경우 iOS, Android 공통 기능 개발을 우선으로 하고 있어 팀 내부에서 Android에서의 기능 확인도 필요한 점 참고 부탁드립니다.

감사합니다.

**Comment by spin-nhn** [comment]
@Kwansik-Jung 님 안녕하세요.
WebView v2.2.0에 해당 기능이 개선되었습니다 :)
확인 부탁드립니다.

**Comment by spin-nhn** [comment]
@Kwansik-Jung 님 안녕하세요.
요청하신 기능은 WebView 2.2.0에서 개선되었습니다.
확인 요청을 드렸으나, 오랜 기간 답변이 없으셔서 해당 이슈는 종료 처리하겠습니다.

추가 이슈가 있을 경우, 새로운 문의 티켓으로 등록해 주시기 바랍니다. 감사합니다.
