### ISSUE TITLE
ios 웹뷰 에서 발생하는 모달 다이어로그 콜백

### ISSUE THREAD

**Issue by Nautilus0409** [nhn/gpm.unity#436]
## Service

* [v] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.

## Summary
ios 에서 웹뷰 에서 발생하는 모달 다이얼로그 의 입력 콜백을 받을 수 있는 방법이 있을까요?

아래 사진의 표시한 취소 버튼을 눌렀을때 콜백 을 받고싶습니다.

## Screenshots
![image](https://github.com/nhn/gpm.unity/assets/76603104/207646da-f8d4-4fa8-8d5a-2fa9e5aa167a)

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Nautilus0409 님.

전달해 주신 기능에 대해 확인해 보겠습니다.
스크린샷을 보면 애플로그인의 디바이스 팝업으로 보이는데요.
WebView를 통해 해당 웹페이지에 접근할 수 있는 URL을 공유해 주시면 감사하겠습니다.

추가로 개발 환경에 대한 내용 공유 부탁드립니다.
* Unity Editor version
* Target SDK
* Target minimum iOS Version

감사합니다.

**Comment by Nautilus0409** [comment]
답변 감사합니다.

Unity Editor version : 2021.3.16f1

Target SDK : 33

Target minimum iOS Version : 12

https://appleid.apple.com/auth/authorize?response_type=code&v=1.0.0&response_mode=form_post&client_id=com.superplanet.archmage.signin&redirect_uri=https://ntusdev.com/auth/apple&state=

해당 링크로 진행해보시곘습니까?

**Comment by Nautilus0409** [comment]
GpmWebView.ShowUrl(
            url,
            new GpmWebViewRequest.Configuration()
            {
                style = GpmWebViewStyle.FULLSCREEN,
                isClearCookie = true,
                isClearCache = true,
                isNavigationBarVisible = true,
                orientation = GpmOrientation.PORTRAIT,
                navigationBarColor = "#000000",
                title = "Apple 계정으로 로그인",
                isBackButtonVisible = false,
                isForwardButtonVisible = false,
                supportMultipleWindows = false,
#if UNITY_IOS
            contentMode = GpmWebViewContentMode.MOBILE
#endif
            },
            OnCallback);

이렇게 출력했는데요, 원래 ios 환경에선 title이 출력이 안되나요? 닫기 버튼도 나오지 않아서요.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Nautilus0409 님.

전달해 주신 Url로 접근해 로그인을 진행했을 때, 스크린샷의 팝업이 노출되지는 않고, Json 형태의 응답값이 호출되었습니다.

아래 링크를 먼저 참고 부탁드립니다.
[Apple 로그인 지원](https://blog.unity.com/kr/technology/support-for-apple-sign-in)
[Apple 로그인 개요](https://developer.apple.com/kr/sign-in-with-apple/)

WebView title및 닫기 버튼이 나오지 않는 경우 가이드 문서의 [GPMWebView.bundle 항목](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#gpmwebviewbundle) 설정 추가 부탁드립니다.

추가 문의 사항이 있으시면 언제든 편하게 연락 부탁드립니다.
감사합니다.

**Comment by Nautilus0409** [comment]
로그인이 되어있는 iOS 디바이스에서 시도해야 해당현상을 확인 할 수 있습니다.

**Comment by spin-nhn** [comment]
@Nautilus0409 님 안녕하세요.
Apple ID 로그인의 주체는 GPM WebView가 아닌 웹 페이지이므로, 로그인 닫기 버튼의 이벤트를 수신할 수 없습니다. 이 문제를 해결하기 위한 최선의 방법은 Apple JS 라이브러리를 사용하는 것으로 예상됩니다. 

자세한 사용 방법은 아래 가이드를 참고해 주시기 바랍니다.

* [Sign in with Apple JS](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple)

이슈 처리가 완료된 후 GPM WebView와의 상호 작용이 필요할 경우, scheme을 사용하시기 바랍니다.

* https://github.com/nhn/gpm.unity/tree/main/docs/WebView#showurl

감사합니다.

**Comment by spin-nhn** [comment]
추가 문의 사항은 새로운 티켓으로 등록 부탁 드립니다. 
감사합니다.
