### ISSUE TITLE
iOS환경, NavigationBar Close버튼이 보이지 않습니다.

### ISSUE THREAD

**Issue by Jeongdo-letsee** [nhn/gpm.unity#439]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
GPM Webview 1.12.2 

## Describe the bug
iOS환경에서 NavigationBar의 버튼들이 보이지 않습니다. 하지만 기능 작동은 합니다.

## Screenshots

![IMG_2078](https://github.com/nhn/gpm.unity/assets/91940238/8455ed87-c9a2-4321-81cb-420986bed8dd)
왼쪽 iPhone 13 ProMax / 오른쪽 Galaxy s21 Ultra 5G
### Unity
Unity 2021.3.28

### Smartphone (please complete the following information):
 - Device: iPhone 13 pro max
 - OS: iOS 16.6

**Comment by taehyeon-nhn** [comment]
안녕하세요. @Jeongdo-letsee 님.

WebView 가이드의 [GPMWebView.bundle](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md#gpmwebviewbundle)을 추가한 후 다시 한 번 테스트 부탁드립니다.

감사합니다.

**Comment by Jeongdo-letsee** [comment]
@taehyeon-nhn 
가이드를 따라 GPMWebView.bundle을 추가하여도 동일한 상태입니다. 
다만 이상한 점은 GPMWebView.bundle이 기본적으로 생성되지않아 Assets/GPM/WebView/Plugins/iOS/GPMWebView.bundle파일[그림1]을 Unity iOS build dir에 복제[그림2] 하여 넣었습니다. 또 이 파일은 0byte로 확인됩니다.

<img width="1619" alt="스크린샷 2023-09-21 오전 10 27 50" src="https://github.com/nhn/gpm.unity/assets/91940238/895ff2c2-c6aa-4721-85d0-7eae079b2795">
[그림1]
![image](https://github.com/nhn/gpm.unity/assets/91940238/cda58885-400d-4713-ac38-559fa755d427)
[그림2]

**Comment by taehyeon-nhn** [comment]
@Jeongdo-letsee님.
GPMWebView.bundle 파일은 현재 버전 기준 약 86KB의 용량을 가져야 합니다.
Game Package Manager를 통해 WebView 삭제 후 재설치를 부탁드립니다.

동일하게 GPMWebView.bundle 파일의 용량이 0바이트로 표시된다면 백신 등의 외부 요인에 의해 파일이 변경되는지 확인이 필요합니다.

감사합니다.
