### ISSUE TITLE
Webview can't work

### ISSUE THREAD

**Issue by hagu0316** [nhn/gpm.unity#444]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
2022.3.10f1

## Summary
My webview on android devices can't work.

## Additional context
Hi, this is my first time asking question on github, I am using unity to present webview on android device, but when I finished all the steps on YT video, it shows that the button has been clicked(Debug.Log) and because it's on PC so it can't show the webview, however when I test my app on android device or simulator, there's no response, further more I can't apply sample scene in the device, it shows error when installing, can anyone help me fix the problem ASAP? Thank you!

**Comment by SangYun-nhn** [comment]
@hagu0316 
Thank you for using GPM.

Please note that the person in charge will be on vacation until Tuesday, October 3, Korean time.

**Comment by taehyeon-nhn** [comment]
Hello. @hagu0316.

Please make sure you are following the [guidelines](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.en.md#android).
If you've followed the above, we'd like to know more about your build.
* Unity Editor version
* Android min/target SDK version
* Gradle configuration information
* Sample code

Thank you.

**Comment by spin-nhn** [comment]
@hagu0316 
As there has been no further response for a long time, this issue is closed.
If further issues arise, please contact us with a new ticket.
