### ISSUE TITLE
WebView Fullscrene doesnt work

### ISSUE THREAD

**Issue by Kudakster** [nhn/gpm.unity#445]
## Service

* [ ] WebView

## Version
Last version

## Describe the bug
Try to use WebView in fullscrene mode doesnt work.

![photo_2023-10-05_11-15-14](https://github.com/nhn/gpm.unity/assets/95761962/7f6e5a83-9f38-4b56-8674-a19685072a8b)

### Unity
- Version 2021.3.20f1

### Desktop (please complete the following information):
 - OS: Android

**Comment by taehyeon-nhn** [comment]
Hello. @Kudakster.

We've verified that both horizontal and vertical views work in the Unity 2021.3.20f1 Android environment.
Please make sure there are no changes to the script code or Sample.unity file.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @Kudakster.

We'll check it out and let you know in the comments.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @Kudakster.

Fixed position and size calculation error in webview v2.0.1.
[Release Notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.en.md#201)

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @Kudakster.

Close this issue.
If you have any questions, please feel free to contact us.

Thank you.
