### ISSUE TITLE
WebView Fullscreen mode wired size

### ISSUE THREAD

**Issue by max60213** [nhn/gpm.unity#446]
## Service

* [ ] WebView

## Version
2022.3.10f1

## Describe the bug
Webview fullscreen mode not showing in fullscreen, or neither does any mode of webview show up properly.

## Screenshots
![Screenshot_20231006-135723_AR Camera](https://github.com/nhn/gpm.unity/assets/96217023/7d6468bd-bcd1-496b-8e51-e17dc96612e4)

## Environment
Unity Android

- Version

### Desktop (please complete the following information):
 - OS: Windows 11
 - 

### Smartphone (please complete the following information):
 - Device: Pixel 3
 - OS: Android 13

**Comment by taehyeon-nhn** [comment]
Hello. @max60213.

We'll check it out and let you know in the comments.

Thank you.

**Comment by CagataySurf** [comment]
Is this issue intruduced with the latest version of webview ? If so, is there any way to change and downgrade webview version ?

**Comment by taehyeon-nhn** [comment]
Hello. @max60213.

The issue only occurs in the latest version. To downgrade GPM WebView, please follow the path below.
[GPM WebView](https://github.com/nhn/gpm.unity/tree/main/release/WebView)

Thank you.

**Comment by CagataySurf** [comment]
> Hello. @max60213.
> 
> The issue only occurs in the latest version. To downgrade GPM WebView, please follow the path below. [GPM WebView](https://github.com/nhn/gpm.unity/tree/main/release/WebView)
> 
> Thank you.

Thanks for the help.

**Comment by taehyeon-nhn** [comment]
Hello. @max60213.

Fixed position and size calculation error in webview v2.0.1.
[Release Notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.en.md#201)

Thank you.

**Comment by max60213** [comment]
Huge Thanks, It Works!!!

**Comment by taehyeon-nhn** [comment]
Hello. @max60213.

Close this issue.
If you have any questions, please feel free to contact us.

Thank you.
