### ISSUE TITLE
Get API callbacks to unity from webview page

### ISSUE THREAD

**Issue by ViktorTolstov** [nhn/gpm.unity#449]
## Service

WebView

## Version
Write the version that you are currently using.
GPM 2.0.1

## Summary
Need to send some data from the WebView page to the Unity game (sign-in data), but trying to implement this can't find any API for that, found similar questions in issues, but didn't find the answer for my question

Similar to https://github.com/nhn/gpm.unity/issues/217, but didn't find any docs or API in the project for that

**Comment by taehyeon-nhn** [comment]
Hello. @ViktorTolstov.

We provide a URL scheme as a method to retrieve data from a webpage through WebView.
In this case, the scheme needs to be invoked with the data appended to the URL.

Thank you.

**Comment by ViktorTolstov** [comment]
Thank you, this helps

My solution if this helps someone:

`<button id="test">Click</button>

<script>
    const button = document.getElementById("test");

    button.addEventListener("click", buttonEventHandler);

    function buttonEventHandler(event){
        console.log('Button click:', event.detail);
        location.href = "CUSTOM_SCHEME://host?param1=value1&param2=value2"
        button.remove();
    }
</script>
`

`GpmWebView.ShowUrl(
                "https://3571-62-84-32-234.ngrok-free.app/",
                
                GetConfiguration(),
                OnWebViewCallback,
                new List<string>()
                {
                    "CUSTOM_SCHEME"
                });`
                
this makes callback in OnWebViewCallback method with all data

Thank you!
