### ISSUE TITLE
IOS the configuration is not working correctly

### ISSUE THREAD

**Issue by deviousfox** [nhn/gpm.unity#450]
## Service

* [ ] WebView

### Unity
- Unity 2020.3.27f1 WebView 2.0.0

### Smartphone (IPhone):
 - Device: [iPhone 15 pro]
 - OS: [17.0.3]
 - Browser [default]
 - Version [default]

## Screenshots
![2023-10-15_20-15-27](https://github.com/nhn/gpm.unity/assets/52548650/62d2a07d-3a47-4be5-8098-5af4f50db578)
![image](https://github.com/nhn/gpm.unity/assets/52548650/85aee4a1-f49c-4936-a52b-54f8f35540b6)

## Describe the bug
In the configuration, I turn off the display of the close button (1 image, line 89) and force an empty title (1 image, line 86). But these changes do not occur in the finished assembly.

## To Reproduce
1. Install sdk & webview plugin
2. build for ios iphone+ipad sdk min ios version 12.0
3. launch on target device 

## Expected behavior
The close button is not displayed, the title is not displayed

**Comment by taehyeon-nhn** [comment]
Hello. @deviousfox.

iOS close button has been fixed in WebView v2.0.2.
For title, please set a space instead of an empty string.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @deviousfox.

Close this issue.
If you have any questions, please feel free to contact us.

Thank you.
