### ISSUE TITLE
TerrainData objects do not get their dependencies mapped

### ISSUE THREAD

**Issue by Monsoonexe** [nhn/gpm.unity#460]
## Service

* [ ] WebView
* [X ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
1.2.2

## Development Environment
Unity 2019.4.40 LTS

## Current Behavior
Objects that are referenced by TerrainData unity objects do NOT get mapped by the Asset Map. Assets (like textures and materials) do not show links to TerrainAssets, which incorrectly shows them as "unused", and the asset map does not show a relationship.

## Expected Behavior
Objects that are referenced by TerrainData unity objects DO get mapped by the Asset Map. Meaning prefabs in the 'trees' list, and materials used.

**Comment by Monsoonexe** [comment]
This is actually a 1-line fix. If this feature is desired, I could make a pull request for it.

**Comment by smflt-nhn** [comment]
This has been fixed and reflected in 1.2.4.
