### ISSUE TITLE
How to fullscreen videos in WebView?

### ISSUE THREAD

**Issue by muhd-anwar** [nhn/gpm.unity#462]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Unity Version 2021.3.29f1
GPM Version 2.2.5
WebView Version 2.0.2

## Summary
I can't seem to be able to fullscreen videos. In YouTube for example, pressing fullscreen button does nothing.

## Screenshots
![asdsadasdsadc](https://github.com/nhn/gpm.unity/assets/10339127/88e9721c-20c8-48a8-8706-fa70899f7512)

**Comment by taehyeon-nhn** [comment]
Hello. @muhd-anwar.

We'll test and see what happens and let you know in the comments.

Thank you.

**Comment by spin-nhn** [comment]
Hello. @muhd-anwar 

After fixing the issue, it will be applied to the next distribution. Thank you for waiting.

**Comment by spin-nhn** [comment]
Hello. @muhd-anwar 
This feature has been improved in WebView v2.2.0 :)
Please check.

**Comment by spin-nhn** [comment]
Hello. @muhd-anwar 
This feature has been improved in WebView v2.2.0 :)
We have requested verification, but since there has been no response for a long time, we will close the issue.
If there are any additional issues, please register a new inquiry ticket. Thank you.
