### ISSUE TITLE
how can i make GPM WebView Support CLEARTEXT sites? 

### ISSUE THREAD

**Issue by jacobLsky1** [nhn/gpm.unity#474]
## Service

* [X] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.
2.0.2

## Summary
i have a clear text index.html file on my server that i want to shoe

## Screenshots
![Screenshot_20240305-160831 1](https://github.com/nhn/gpm.unity/assets/62054080/1d3ffb88-7441-41dc-8cf1-73d6711dec12)

## Additional context
nothing more to add

**Comment by spin-nhn** [comment]
Hello. @jacobLsky1 

Try adding the usesCleartextTraffic attribute to the application tag in AndroidManifest.xml.

```xml
<application android:usesCleartextTraffic="true">
       ...
</application>
```

thank you.

**Comment by jacobLsky1** [comment]
yes. this fixed the issue, thank you!

**Comment by spin-nhn** [comment]
We are very happy that the issue has been resolved.
We look forward to seeing great apps using the GPM service.
thank you.
