### ISSUE TITLE
WebView is not loading in the assets folder

### ISSUE THREAD

**Issue by nitingit7** [nhn/gpm.unity#485]
## Service

* [ ] WebView

## Version
2.9.0

## Describe the bug
Webview is not loading in the assets folder, and it is giving error in the entire code where using Gpm.WebView; is using

![Source](https://github.com/nhn/gpm.unity/assets/119484935/fe2850b8-724a-4a5b-a145-03547f270f96)

**Comment by taehyeon-nhn** [comment]
Hello. @nitingit7.

What is the Unity version using WebView?
Is it the same when you first created the project?
Please provide a more detail.

Thank you.

**Comment by nitingit7** [comment]
> Hello. @nitingit7.
> 
> What is the Unity version using WebView? Is it the same when you first created the project? Please provide a more detail.
> 
> Thank you.

I am using unity version 2023.2.11f1, and it is same when I first created the project, nothing is changing/adding in my assets folder. Any further information you want, you can ask me freely.

**Comment by taehyeon-nhn** [comment]
Hello. @nitingit7.

We've confirmed that there are no issues installing GPM Webview on Unity 2023.2.11f1.
It might help to try reinstalling Unity Editor.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @nitingit7.
There's nothing more to add, so we'll close the issue.
Thank you.
