### ISSUE TITLE
WebView overlay UGUI 문의드립니다.

### ISSUE THREAD

**Issue by ParkEunSeong** [nhn/gpm.unity#486]
## Service

* [x] WebView

## Version
2.2.5

## Summary
WebView overlay UGUI 가능 여부

## Screenshots
If applicable, add screenshots to help explain your question.

## Additional context
유니티 옵션 Render Over Native UI 를 활성화한 후 웹뷰 위에 있는 UGUI 버튼 이벤트가 먹히지 않습니다.
어떻게하면 이벤트를 발생시킬 수 있는지 확인해주시면 감사하겠습니다.

**Comment by taehyeon-nhn** [comment]
안녕하세요. @ParkEunSeong님.

현재 Webview는 Popup 형태의 영역과 그 외 Unity 영역으로 구분되어 이벤트가 처리되게 개발되었습니다.
Unity 설정으로 Webview 영역 안에서의 이벤트 발생이 가능한지 여부는 확인이 필요하며 추후 댓글을 통해 내용 전달드리겠습니다.

감사합니다.
