### ISSUE TITLE
Infinite Scroll 관련 문의드립니다.

### ISSUE THREAD

**Issue by ParkEunSeong** [nhn/gpm.unity#489]
## Service

* [x] UI

현재 스크롤이 이동한 만큼 스크롤 다른 오브젝트를 동일한 속도로 이동시킬려고하는데
어떤 변수를 참조하면 될까요?

**Comment by smflt-nhn** [comment]
@ParkEunSeong

안녕하세요. 

실시간 변화를 알고 싶으시면 ScrollRect의 OnValueChanged로 들어오는 값으로 알 수 있습니다.
위치로 알고 싶으시다면 InfiniteScroll의 GetContentPosition()을 참고하시면 될것 같습니다. 

감사합니다.

**Comment by ParkEunSeong** [comment]
Movement Type 이 Clamped 인 경우 값이 정확하게 들어오지 않는 것 같은데 확인할 수 있는 방법 있을까요?

아래 스샷 참고해주시면 감사하겠습니다.
![image](https://github.com/nhn/gpm.unity/assets/11013810/b8eabf39-318b-4d56-9367-05569f1f7551)

**Comment by smflt-nhn** [comment]
@ParkEunSeong 

현재 최신 버전에서 확인해보았을때 정상적으로 들어오는것으로 보이는데 버전 확인 부탁드립니다.
현재 UI 최신버전은 2.9.0입니다.
감사합니다.

**Comment by ParkEunSeong** [comment]
감사합니다.
