### ISSUE TITLE
Webview can't Open in ios

### ISSUE THREAD

**Issue by vayne666** [nhn/gpm.unity#499]
## Service

- [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
gpm_webview_v2.0.2
ios15.4.1
xcode15.3

## Summary
I have three urls that
https://account.zogilabs.io/signup
https://account.zogilabs.io/profile
https://mblk.bezogia.com/#/privacy

but in ios ,only the first can open

## Screenshots
If applicable, add screenshots to help explain your question.

## Additional context
runtime log

[GPM][WebView][iOS][GPMWebViewController.m:(962)] Error occurred while loading content. Error Domain=WebKitErrorDomain Code=102 "Frame load interrupted" UserInfo={_WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x282391aa0>, NSErrorFailingURLStringKey=https://mblk.bezogia.com/#/privacy, NSErrorFailingURLKey=https://mblk.bezogia.com/#/privacy, NSLocalizedDescription=Frame load interrupted}

 [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service with pid 10894 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service with pid 10894 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2024-04-01 11:14:50.736398+0800 [44199:16471015] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by AliYang660703** [comment]
I have the same Issue.
Log:[GPM][WebView][iOS][GPMWebViewController.m:(962)] Error occurred while loading content. Error Domain=WebKitErrorDomain Code=102 "頁框載入中斷" UserInfo={_WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x30223efe0>.......
Is there any Follow-up with this problem ?
