### ISSUE TITLE
Webview Close Button Not Visible on IOS Build

### ISSUE THREAD

**Issue by Skybeamer** [nhn/gpm.unity#521]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
2021.3.11f1
GPM 2.0.5

## Summary
WebView Fullscreen for IOS can't see the close button so I cant close the webview but it is there for the android build

## Screenshots
![IMG_7791](https://github.com/nhn/gpm.unity/assets/80440782/ee844c3c-134d-4c31-836d-7b495dc75dd4)

**Comment by SangYun-nhn** [comment]
Hello
Thank you for using GPM.

#439 It may be helpful to refer to similar issues.
If you have any additional questions, please let me know.

**Comment by spin-nhn** [comment]
Hello. @Skybeamer 

Is the problem resolved?

**Comment by Skybeamer** [comment]
Yes, @spin-nhn 
The issue was resolved by following the steps in XCode, i mustve missed it out on accident and not configure the Webview bundle and adding it to the Build Phases. Once i did this, it worked!
