### ISSUE TITLE
GpmWebViewSafeBrowsing.ShowSafeBrowsing 을 사용중인데, IsActive 와 Close로 체크를 하고 싶어요.

### ISSUE THREAD

**Issue by Atto14** [nhn/gpm.unity#522]
안녕하세요.
iOS 환경으로 테스트 중에 궁금한 것이 있어 남깁니다.
GpmWebViewSafeBrowsing.ShowSafeBrowsing 를 이용하여 웹뷰를 띄우고나서 
GpmWebView.IsActive() 를 호출해보니 false 가 찍히더라구요.
그리고 GpmWebView.Close() 를 호출해도 아무런 반응이 없습니다.

혹시 ShowSafeBrowsing  에 대해서는 동작하지 않는 것인지, 버그가 있는 것인지 궁금합니다.

버전 정보)
gpm 버전 2.2.5
webview 버전 2.0.5

**Comment by spin-nhn** [comment]
@Atto14 님 안녕하세요.
GPM WebView를 이용해 주셔서 감사합니다.

SafeBrowsing Close는 GPM WebView에서 지원 않는 기능입니다.
Google이 제공하는 API도 없고, 다른 방식으로 제공은 가능할 듯 보이나 여러 제약 사항(launchMode, minSdkVersion 상향 등)이 발생하게 되어 내부 논의 중에 있습니다. 
지원 방향이 결정되면 다시 안내드리겠습니다.

감사합니다.

**Comment by spin-nhn** [comment]
추가로 GPM WebView API 중 Close와 IsActive는 웹뷰에서만 지원되는 기능이며 SafeBrowsing에서는 지원되지 않습니다.

감사합니다.

**Comment by spin-nhn** [comment]
@Atto14 님 안녕하세요.
iOS 문의셨군요. 죄송합니다.
iOS는 Close 기능을 제공하는데 문제가 없으므로 추후 제공될 예정이며, isActive 기능은 추가 확인이 필요합니다.
Android 제공 방식이 결정되면 다시 덧글로 공유 드리겠습니다.

**Comment by Atto14** [comment]
> @Atto14 님 안녕하세요. iOS 문의셨군요. 죄송합니다. iOS는 Close 기능을 제공하는데 문제가 없으므로 추후 제공될 예정이며, isActive 기능은 추가 확인이 필요합니다. Android 제공 방식이 결정되면 다시 덧글로 공유 드리겠습니다.

답변 감사합니다.

**Comment by spin-nhn** [comment]
@Atto14 님 안녕하세요.

혹시 Android도 서비스 예정이신가요?
Android의 경우,  Android 8.1(API 27) 이상에서는 지원이 가능할 듯 한데, 그 미만 버전은 지원이 힘들 것 같습니다.
Android 8.1(API 27) 이상에서만 지원되어도 괜찮을까요?

**Comment by Atto14** [comment]
네 맞습니다.
현재 Target API Level 은 33으로 설정중이며, 향후 구글 정책  관련하여 34로 설정할 예정입니다.

**Comment by spin-nhn** [comment]
@Atto14 Target API Level을 33으로 해도 사용자 단말기가 26 이하일 경우 지원이 되지 않습니다. 이 경우에도 문제가 없을지 확인 부탁드리겠습니다. (26 이하 일 경우에는 특정 오류 코드 전달)

**Comment by Atto14** [comment]
현재 해당 기능이 없는 채로 사용하고 있으며, 제 입장에서 반드시 포함되어야 하는 내용이 아닙니다.
그냥 해당 이슈 자체가 R&D 과정에서 테스트 시에 예상대로 동작하지 않아 문의드리는 내용이지, 필요로 하니 기능 구현 부탁드리는 내용이 아닌 점 참고 부탁드립니다.

**Comment by spin-nhn** [comment]
@Atto14 
GPMWebView 2.1.0 버전에 iOS 전용 CloseSafeBrowsing API가 추가되었습니다.
감사합니다.

* [GPM WebView 2.1.0 Release notes](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md)
