### ISSUE TITLE
WebCacheImage의 Request Header 설정 방법 문의

### ISSUE THREAD

**Issue by lklab** [nhn/gpm.unity#523]
## Service

* [ ] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [X] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Common 2.4.0
UI 2.9.0
CacheStorage 1.3.1

## Summary
안녕하세요 GPM을 유용하게 업무에 활용하고 있는 사람입니다. 감사합니다.
`WebCacheImage.SetUrl()` 함수에 URL을 전달하면 해당하는 이미지를 다운로드할 수 있는데, 저희 서버 정책 상 request header에 인증 키를 포함해야만 이미지를 다운로드 할 수 있는 상황이라 이에 관해 문의 드립니다.

1. 현재 버전에서 custom request header를 추가할 수 있는 방법이 있나요?
2. 만약 없다면 이후 버전에서 해당 방법을 추가하실 계획이 있으신가요?

일단은 `WebCacheImage.SetUrl()` 함수를 `SetUrl(string url, Dictionary<string, string> headers = null)`로 수정하고 `CachePackage.Request()` 함수까지 모든 call stack 상에 있는 모든 함수들에 동일하게 `headers` 파라미터를 추가한 후, `CachePackage.Request()` 내부의 `GpmWebRequest`를 생성하는 부분에서 custom request header를 추가하는 식으로 구현을 변경하여 사용 중입니다. 참고 부탁 드립니다.

**Comment by smflt-nhn** [comment]
@lklab

안녕하세요.
문의에 답변드립니다.

1. 현재 버전에선 미 지원이라 사용하신 것처럼 구현을 추가하여 사용하시면 됩니다.
2. 해당 기능이 지원되도록 다음 버전에 추가할 예정입니다.

감사합니다.

**Comment by lklab** [comment]
답변 감사합니다. 일단 수정해서 사용하다가 다음 버전에 추가되면 업데이트해서 사용해야겠네요!

**Comment by smflt-nhn** [comment]
@lklab 
안녕하세요. UI 2.10.0, CacheStorage 1.4.0에 Header 추가 기능 추가되어 배포되었습니다.

**Comment by lklab** [comment]
@smflt-nhn 정말 감사합니다. 잘 쓰겠습니다. ^^
