### ISSUE TITLE
My webview page Zoom function is not working properly

### ISSUE THREAD

**Issue by eason112** [nhn/gpm.unity#529]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
webview 2.1.0
unity 2022.3.22f1

## Describe the bug
When I first open the page I can zoom, but I close and then open it again I can't.

**Comment by spin-nhn** [comment]
Hello @eason112.
If you could share the SDK version and OS information you are using, I will check and get back to you.

**Comment by eason112** [comment]
my OS is Android and API33

**Comment by spin-nhn** [comment]
@eason112 
After fixing the issue, it will be applied to the next distribution. Thank you. 😄

**Comment by eason112** [comment]
Thank you. So this is the plugin's promblem? I don't know if this is my problem here.

**Comment by spin-nhn** [comment]
@eason112 
Zoom related settings are missing and will be added.
We will try to distribute it in early September.

**Comment by eason112** [comment]
OK, Thank you very much!

**Comment by eason112** [comment]
Hi, I want to know if there is a chance to update next week. Thanks!

**Comment by spin-nhn** [comment]
@eason112 
Hi. We are planning to update this within this week.

**Comment by eason112** [comment]
I saw the update, and the problem has been solved. Thanks!

**Comment by spin-nhn** [comment]
Hello. @eason112 
I'm glad it worked out for you :)
Thank you for sharing your results.
