### ISSUE TITLE
[iOS][Webview] NavigationBar Title Not Show(but closeButton Show)

### ISSUE THREAD

**Issue by ariplates** [nhn/gpm.unity#530]
## Service

* [x] WebView
* [ ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
WebView 2.1.0

## Describe the bug

iOS 에서 팝업모드로 웹뷰 사용을 하였는데
Close버튼은 정상적으로 뜨나
제목이 뜨지 않는 상황입니다.

## Screenshots

![윗 설명 박스 없는 화면](https://github.com/user-attachments/assets/97845577-42ff-4d36-a167-23a2dcad0a27)
![2024-09-02 10 13 29](https://github.com/user-attachments/assets/69c60b1a-1e57-4c24-8cf4-0927d587d700)

### Unity
- Version 2022.3.27f1

### Smartphone (please complete the following information):
 - OS: [e.g. iOS8.1] iOS

**Comment by spin-nhn** [comment]
@ariplates 
확인 후 답변드리겠습니다.

**Comment by spin-nhn** [comment]
@ariplates 님 안녕하세요.
iOS Popup에서는 NavigationBar를 지원하지 않습니다.
아래와 같이 기능 지원은 가능하겠으나,

![image](https://github.com/user-attachments/assets/98eac791-5f42-410e-98a2-4a8afa346d35)

iOS는 팝업은 아래와 같이 NavigationBar가 노출되지 않는 것이 일반적이라 NavigationBar를 노출하는 것을 추천 드리지는 않습니다.

![image](https://github.com/user-attachments/assets/9bcf0e68-8433-4145-b971-9d14c518d728)![image](https://github.com/user-attachments/assets/fa586719-d5bd-4e52-b7c2-c5187b26987d)


관련 기능이 개발에 꼭 필요한 사항이라면 내부 논의 후 결정이 필요할 것으로 판단됩니다.
추가 의견 부탁드립니다.

**Comment by spin-nhn** [comment]
@ariplates 님 안녕하세요.
관련하여 지금도 NavigationBar가 필요한 상황이실까요?

**Comment by ariplates** [comment]
> @ariplates 님 안녕하세요. 관련하여 지금도 NavigationBar가 필요한 상황이실까요?

안녕하세요.  
필요하지 않는 상황입니다.

말씀주셨던바와 같이 iOS 에는 팝업에서 노티바를 통상적으로 사용하지 않는다는 부분을 팀내 공유하였고,
현상황 그대로 사용하기로 결정하였습니다.
감사합니다!

**Comment by spin-nhn** [comment]
@ariplates 
공유 감사합니다 :)

해당 이슈는 종료 처리하도록 하겠습니다.
감사합니다.
