### ISSUE TITLE
AssetMapData does not correctly find all scene dependencies

### ISSUE THREAD

**Issue by Monsoonexe** [nhn/gpm.unity#540]
## Service

* [ ] WebView
* [X ] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Describe the bug
GPM's strategy for finding scene dependencies is to iterate through only GameObjects in the scene. This strategy ignores system assets like TerrainData, LightingSettings, LightingData, OcclusionData, etc. 

An example of how this hurts you is that the AssetMapGraph will not show a link between a scene and its Skybox material. Also, maybe system assets will erroneously show up as "unused", according to GPM.

To make matters worse, scenes are imported 2 different ways. The first time a scene is imported, its dependencies are found using Unity's api. The 2nd time, dependencies are found using GPM's api. The result of this is that, depending on timing, you'll see different results in the AssetGraphMap. You'll get correct results until the node redraws, which re-imports scenes using the GPM dependency check, therefore changing the graph.

So the graph relationships change while you're looking at it.

## To Reproduce
1. Create a brand new scene.
2. Go to lighting tab
3. Create new LightingSettings
4. Assign a skybox material
5. click skybox material and press Show AssetMap
6. Notice there is no link between scene and material.
7. right-click re-import scene.
8. Notice there is now a link

## Expected behavior
GPM should detect ALL dependencies, even system dependencies, without requiring the user to "Reimport" until GPM gets into an acceptable state.

**Comment by smflt-nhn** [comment]
1.2.4에 수정되어 반영되었습니다.
