### ISSUE TITLE
GetDependencyInfo.cs - FindProperty 함수의 parameter null check

### ISSUE THREAD

**Issue by masteage** [nhn/gpm.unity#541]
## Service

* [ ] WebView
* [x] AssetManagement
* [ ] Communicator
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [ ] Profiler
* [ ] Adapter
* [ ] DLST

## Version
Write the version that you are currently using.
Version 2.2.6 - May 18, 2024
2.2.6 (Current) - released on May 18, 2024
Original - released on September 30, 2019

## Describe the bug
어셋 관리 사용을 하기 위해 설정 중 error 발생 및 무한 대기.

## To Reproduce
(1) GPM 설치
(2) AssetManagement 설치
(3) Tool -> GPM -> AssetManagement -> Find Reference (에셋 찾기)
(4) "에셋관리 사용하기" 버튼
(5) progress 도중 error 발생, 무한 대기.

## Expected behavior
실제로 연결이 끊어진 리소스들이 꽤 있는 상태인데, 최초 설치 및 세팅시에 null 로 인해 설정 자체가 안되면 문제 인듯 합니다.

~\Assets\GPM\AssetManagement\Editor\AssetMap\GetDependencyInfo.cs

        private void FindProperty(Object checkObject)
        {
            // checkObject 의 null check 필요.
            //if (findObj.Contains(checkObject.GetInstanceID()) == true)
            if (checkObject == null || findObj.Contains(checkObject.GetInstanceID()) == true)
            {
                return;
            }
        ....
        }

### Unity
- Version 2021.3.34f1

### Desktop
- Windows 11 Pro

**Comment by smflt-nhn** [comment]
@masteage 제보해주셔서 감사합니다. 수정하여 배포하겠습니다.

**Comment by smflt-nhn** [comment]
1.2.4에 수정되어 반영되었습니다.
