### ISSUE TITLE
현재 url은 어떻게 얻어오나요?

### ISSUE THREAD

**Issue by p0708jh** [nhn/gpm.unity#71]
## Service

* [ ] Adapter
* [ ] AssetManagement
* [ ] Communicator
* [ ] DLST
* [ ] LogViewer
* [ ] Manager
* [ ] UI
* [x] WebView

## Version
Write the version that you are currently using.

## Development Environment
Write the version of Unity, OS and so on.

## Current Behavior
Write a description of the current operation.

## Expected Behavior
Write a description of the future action.

**Comment by spin-nhn** [comment]
@p0708jh 안녕하세요 :)

현재 URL을 가져올 수 있는 방법에 대해 문의하셨습니다.

---

답변에 앞서 몇 가지 궁금한 사항이 있습니다.

1. 페이지 로드 완료 후의 URL이 필요하신가요? 아니면 Redirection URL 모두가 필요하신 건가요?
2. 애플리케이션의 어떤 기능 구현에 필요한 기능인가요? (어떻게 사용 예정이신가요?)

**Comment by p0708jh** [comment]
안녕하세요 친절한 답변 감사합니다 :)
페이지 로드 완료 후의 URL만 있으면 됩니다!
redirection url은 제가 따로 파싱하면 돼서 괜찮습니다.
oauth 로그인 구현중에 필요합니다!

페이지 로드 완료후의 URL 만 필요합니다 감사합니다!

**Comment by p0708jh** [comment]
추가로 쿠키와 캐시를 삭제하는 기능도 필요합니다!

**Comment by spin-nhn** [comment]
@p0708jh 
페이지 로드 완료 후 URL을 가져오는 기능과 쿠키 캐시를 삭제하는 기능이 필요하시군요.

해당 기능은 내부 논의 후, 내일 답변드리겠습니다. :)

**Comment by spin-nhn** [comment]
@p0708jh 안녕하세요.
내부 논의된 내용 공유드립니다.

요청 주신 기능들은 추후 추가하기로 결정되었습니다.
다만 일정은 아직 잡히지 않았구요. 진행 시 마일스톤 등록 후 공유드리도록 하겠습니다.
감사합니다 즐거운 하루 되십시오.

### 요청 기능

* 페이지 로드 완료 후 URL을 가져오기 : 적용
* Cookie, Cache 삭제 : 적용

---

GPM 서비스를 사용해 주셔서 감사합니다.
AssetStore 리뷰 등록은 저희에게 큰 힘이 됩니다 :)

**Comment by spin-nhn** [comment]
@p0708jh 안녕하세요.
금일 GPM WebView v1.2.0이 업데이트 되었습니다.

* Guide
  * https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.md
* Release note
  * https://github.com/nhn/gpm.unity/blob/main/docs/WebView/ReleaseNotes.md

요청하신 쿠키, 캐시 삭제 기능이 추가되었으며 Navigation Bar 숨김 기능도 추가되었습니다.
페이지 로드 완료 후 URL을 가져오기 기능은 구현상의 시간이 필요하여 다음 업데이트 시 적용될 예정입니다.

---

GPM 서비스를 사용해 주셔서 감사합니다.
AssetStore 리뷰 등록은 저희에게 큰 힘이 됩니다 :)
